# Mattis EDA

Initial loading and first overview inspection for data in `data/raw/Alternative Medien/`.

In [112]:
from pathlib import Path
import pandas as pd

In [113]:
# Set Path
PROJECT_ROOT = Path.cwd().parent
BASE_DIR = PROJECT_ROOT / "data" / "raw" / "Alternative Medien"

print("cwd:", Path.cwd())
print("PROJECT_ROOT:", PROJECT_ROOT)
print("BASE_DIR:", BASE_DIR)
print("exists:", BASE_DIR.exists())

if not BASE_DIR.exists():
    raise FileNotFoundError(f"BASE_DIR not found: {BASE_DIR}")

cwd: /Users/MattisHaumann/Dev/Thesis/Initial EDA
PROJECT_ROOT: /Users/MattisHaumann/Dev/Thesis
BASE_DIR: /Users/MattisHaumann/Dev/Thesis/data/raw/Alternative Medien
exists: True

In [114]:
# CSV reader (for every source except RT)
def read_csv_resilient(csv_path: Path) -> pd.DataFrame:
    encodings = ("utf-8", "utf-8-sig", "latin-1")

    # normal read
    for enc in encodings:
        try:
            return pd.read_csv(
                csv_path,
                encoding=enc,
                low_memory=False,
                on_bad_lines="skip",
            )
        except Exception:
            pass

    # delimiter sniff (python engine)
    for enc in encodings:
        try:
            return pd.read_csv(
                csv_path,
                encoding=enc,
                sep=None,
                engine="python",
                low_memory=False,
                on_bad_lines="skip",
            )
        except Exception:
            pass

    raise ValueError(f"Could not read: {csv_path}")

In [115]:
dfs_by_source = {}
overview_rows = []

source_dirs = sorted(
    [p for p in BASE_DIR.iterdir() if p.is_dir()],
    key=lambda p: p.name.lower()
)

for source_dir in source_dirs:
    csv_files = sorted(source_dir.rglob("*.csv"))
    frames = []
    failed = 0

    for csv_file in csv_files:
        try:
            part = read_csv_resilient(csv_file)
            part["source"] = source_dir.name
            part["source_file"] = csv_file.name  # keep it simple
            frames.append(part)
        except Exception as e:
            failed += 1
            print(f"[WARN] {source_dir.name} -> {csv_file.name}: {e}")

    df_source = pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()
    dfs_by_source[source_dir.name] = df_source

    overview_rows.append({
        "source": source_dir.name,
        "files_found": len(csv_files),
        "files_failed": failed,
        "total_articles": len(df_source),
        "n_columns": df_source.shape[1],
    })

# RT_de.xlsx at the root
rt_path = BASE_DIR / "RT_de.xlsx"
if rt_path.exists():
    df_rt = pd.read_excel(rt_path)
    df_rt["source"] = "RT_de"
    df_rt["source_file"] = rt_path.name
    dfs_by_source["RT_de"] = df_rt

    overview_rows.append({
        "source": "RT_de",
        "files_found": 1,
        "files_failed": 0,
        "total_articles": len(df_rt),
        "n_columns": df_rt.shape[1],
    })

overview_df = (
    pd.DataFrame(overview_rows)
    .sort_values(["total_articles", "source"], ascending=[False, True])
    .reset_index(drop=True)
)

display(overview_df)

              source  files_found  files_failed  total_articles  n_columns
0      deusch_pravda          496             0          397944          9
1              RT_de            1             0           12390          9
2  Nius_Rohdaten_neu          285             0            4885         29
3             apollo          165             0            3550          7
4   Tichy's Einblick          195             0            3126          8
5            Compact          214             0            2045          6
6        Antispiegel          307             0             914          9
7       Reitschuster          238             0             685          6

In [116]:
src = "deusch_pravda"

if src in dfs_by_source:
    df = dfs_by_source[src]

    if "time" in df.columns:
        # Parse German datetime and drop time part
        parsed = pd.to_datetime(
            df["time"],
            format="%d.%m.%Y, %H:%M",
            errors="coerce"
        )

        df["date"] = parsed.dt.normalize()  # keeps only YYYY-MM-DD

        dfs_by_source[src] = df

        print(f"[OK] {src}: created clean 'date' column (without time)")
    else:
        print(f"[WARN] {src}: no 'time' column found")

[OK] deusch_pravda: created clean 'date' column (without time)

In [117]:
DATE_CANDIDATES = ["Date", "date", "day", "published", "published_at", "datetime", "timestamp"]

date_rows = []

for source, df in dfs_by_source.items():
    date_min = pd.NaT
    date_max = pd.NaT

    for col in DATE_CANDIDATES:
        if col in df.columns:
            s = pd.to_datetime(df[col], errors="coerce").dt.normalize()
            if s.notna().any():
                date_min = s.min()
                date_max = s.max()
                break

    date_rows.append({
        "source": source,
        "date_min": date_min,
        "date_max": date_max,
    })

date_df = pd.DataFrame(date_rows)

overview_df = overview_df.drop(columns=["date_min", "date_max"], errors="ignore")
overview_df = overview_df.merge(date_df, on="source", how="left")

display(overview_df)

,source,files_found,files_failed,total_articles,n_columns,date_min,date_max
0,deusch_pravda,496,0,397944,9,2025-05-05,2025-09-02
1,RT_de,1,0,12390,9,2024-11-14,2026-01-19
2,Nius_Rohdaten_neu,285,0,4885,29,2025-05-01,2026-02-10
3,apollo,165,0,3550,7,2025-08-12,2026-02-10
4,Tichy's Einblick,195,0,3126,8,2025-08-01,2026-02-11
5,Compact,214,0,2045,6,2025-06-11,2026-02-10
6,Antispiegel,307,0,914,9,2025-04-10,2026-02-10
7,Reitschuster,238,0,685,6,2025-06-10,2026-02-10

# Articles per month

In [118]:
DATE_CANDIDATES = ["Date", "date", "day", "published", "published_at", "datetime", "timestamp"]

monthly_rows = []

for source, df in dfs_by_source.items():
    used_series = None

    # find a usable date column
    for col in DATE_CANDIDATES:
        if col in df.columns:
            s = pd.to_datetime(df[col], errors="coerce").dt.normalize()
            if s.notna().any():
                used_series = s
                break

    if used_series is None:
        continue

    # convert to year-month period
    ym = used_series.dt.to_period("M").astype(str)

    # count articles per month
    counts = ym.value_counts()

    for month, count in counts.items():
        monthly_rows.append({"source": source, "year_month": month, "articles": count})

monthly_df = pd.DataFrame(monthly_rows)

pivot = (
    monthly_df
    .pivot_table(index="source", columns="year_month", values="articles", aggfunc="sum", fill_value=0)
    .sort_index()
)

# optional: sort columns chronologically (YYYY-MM already sorts correctly as strings)
pivot = pivot.reindex(sorted(pivot.columns), axis=1)

display(pivot)

year_month,2024-11,2024-12,2025-01,2025-02,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02
source,,,,,,,,,,,,,,,,
Antispiegel,0,0,0,0,0,85,118,34,32,92,122,113,85,114,87,32
Compact,0,0,0,0,0,0,0,168,176,207,275,301,280,258,293,87
Nius_Rohdaten_neu,0,0,0,0,0,0,482,447,495,466,563,589,604,509,548,182
RT_de,522,1031,958,939,941,862,895,785,887,687,856,855,898,868,406,0
Reitschuster,0,0,0,0,0,0,0,65,106,72,100,0,88,0,67,22
Tichy's Einblick,0,0,0,0,0,0,0,0,0,458,486,510,483,504,505,180
apollo,0,0,0,0,0,0,0,0,0,176,565,647,643,635,646,238
deusch_pravda,0,0,0,0,0,0,22016,30688,39674,36574,2249,0,0,0,0,0

## Erste Insights
Klare Unterschiede zwischen den Quellen.

- **deusch_pravda** hat extrem hohe Zahlen, aber nur in wenigen Monaten (Mai–September 2025). Sind wahrscheinlich Telegramdaten und nicht klassisch news

- **RT_de** veröffentlicht konstant über einen langen Zeitraum (Ende 2024–Anfang 2026). Sehr strukturiert und institutionell

- **Nius, Apollo, Compact und Tichys Einblick** zeigen relativ regelmäßige monatliche Output-Zahlen. Auch stabile redaktionelle Routinen vermutlich

- **Antispiegel und Reitschuster** haben deutlich geringeres Volumen. Vermutlich kleinere Strukturen oder stärker meinungsgetriebene Formate.

**Fazit (erste EDA):**  
Schon auf dieser deskriptiven Ebene sieht man, dass die untersuchten „alternativen Medien“ sehr unterschiedlich arbeiten – sowohl im Volumen als auch in der zeitlichen Dynamik.

# Length of Articles

In [119]:
# map using lowercase source names to avoid case issues
TEXT_COLUMN_MAP = {
    "antispiegel": "Full_Text",
    "apollo": "Inhalt",
    "compact": "Inhalt",
    "deusch_pravda": "full_text",
    "reitschuster": "Inhalt",
    "nius_rohdaten_neu": "article_text",
    "rt_de": "Full_Text",
    "tichy's einblick": "article_text",
}

length_rows = []

for source, df in dfs_by_source.items():
    key = source.lower()  # normalize
    text_col = TEXT_COLUMN_MAP.get(key)

    if text_col is None or text_col not in df.columns:
        print(f"[WARN] {source}: text column not found or not mapped. (mapped={text_col})")
        continue

    words = df[text_col].astype(str).str.split().str.len()

    length_rows.append({
        "source": source,
        "articles": len(df),
        "text_col": text_col,
        "mean_words": words.mean(),
        "median_words": words.median(),
        "min_words": words.min(),
        "max_words": words.max(),
    })

length_df = (
    pd.DataFrame(length_rows)
    .sort_values("mean_words", ascending=False)
    .reset_index(drop=True)
)

display(length_df)

,source,articles,text_col,mean_words,median_words,min_words,max_words
0,Antispiegel,914,Full_Text,2203.440919,1720.0,170.0,18894.0
1,Reitschuster,685,Inhalt,1584.382482,1466.0,837.0,5014.0
2,Tichy's Einblick,3126,article_text,827.087332,765.0,42.0,5857.0
3,RT_de,12390,Full_Text,629.242696,470.5,7.0,4689.0
4,Nius_Rohdaten_neu,4885,article_text,586.183498,426.0,6.0,64721.0
5,Compact,2045,Inhalt,504.015159,417.0,23.0,4324.0
6,apollo,3550,Inhalt,444.925634,384.0,23.0,2662.0
7,deusch_pravda,397944,full_text,162.234063,114.0,1.0,7820.0

## Erste Insights 

Klare strukturelle Unterschiede zwischen den Quellen.

- **deusch_pravda** hat extrem hohe Volumina in kurzer Zeit. Gleichzeitig ist die durchschnittliche Textlänge deutlich niedriger. Das spricht für aggregierte Inhalte (z. B. Telegram) statt klassischer redaktioneller Langform.

- **RT_de** sowie **Antispiegel** und **Reitschuster** weisen im Schnitt deutlich längere Texte auf. Das deutet eher auf ausführlichere Beiträge oder kommentierende Formate hin.

- **Nius, Apollo, Compact und Tichys Einblick** liegen im mittleren Bereich. Hier sieht man eher typische Online-Artikel-Längen.

Wichtig:  
Die Textdaten sind teilweise noch stark „roh“. Es finden sich z. B. Werbeeinblendungen, wiederholte Textpassagen oder technische Artefakte. Vor tiefergehenden inhaltlichen Analysen (z. B. Sentiment, Topic Modeling) ist daher eine systematische Textbereinigung notwendig.

**Zwischenfazit:**  
Schon in dieser frühen EDA zeigen sich klare Unterschiede in Produktionslogik, Umfang und Struktur der Inhalte. Die Datenqualität und Textbereinigung werden dabei ein zentraler methodischer Schritt für die weitere Analyse sein.

## Dateninspektion pro Quelle

In [120]:
import random

SAMPLE_SIZE = 5

for source, df in dfs_by_source.items():
    print("\n" + "="*80)
    print(f"Source: {source}")
    print("="*80)

    if len(df) == 0:
        print("No data available.")
        continue

    sample_df = df.sample(min(SAMPLE_SIZE, len(df)), random_state=42)

    for i, row in sample_df.iterrows():
        print("\n--- Article ---")

        # Title if available
        if "title" in df.columns:
            print("Title:", row.get("title"))
        elif "Title" in df.columns:
            print("Title:", row.get("Title"))

        # Try mapped text column if already defined
        text_col = None
        for col in df.columns:
            if col.lower() in ["full_text", "text", "inhalt", "article_text"]:
                text_col = col
                break

        if text_col:
            text_preview = str(row[text_col])[:1000]
            print("\nText Preview:\n", text_preview)
        else:
            print("No obvious text column found.")

================================================================================
Source: Antispiegel
================================================================================

--- Article ---
Title: Beginnt jetzt die „GPS-Show“?

Text Preview:
 Propaganda
Beginnt jetzt die „GPS-Show“?
Schweden meldet eine große Zunahme der Störungen des GPS in der zivilen Luftfahrt. Schuld ist angeblich natürlich Russland und als Beleg erinnert der Spiegel an die Störung des Fluges von von der Leyen, die sich jedoch als Fake herausgestellt hat. Die westliche Propaganda lügt immer lustiger.
von Anti-Spiegel
6. September 2025 12:00 Uhr
Als am Montag gemeldet wurde, das GPS des Fluges von EU-Kommissionschefin Ursula von der Leyen von Warschau ins bulgarische Plowdiw sei von Russland gestört worden und die Maschine hätte deswegen eine Stunde lang Warteschleifen fliegen müssen, bevor die Piloten landen konnten, war schnell klar, dass die Geschichte frei erfunden war.
Die GPS-Lüge vom Montag
Erstens liegt Plowdiw etwa 200 Kilometer vom Schwarzen Meer entfernt, sodass, wenn Russland das GPS gestört hätte, das GPS im halben Bulgarien hätte gestört sein müssen. Zweitens ist es für Piloten kein Problem, ohne GPS zu landen. Das ist Routine, zumal der Ru

--- Article ---
Title: Uneinigkeit in der EU über Reaktion auf Trumps Strafzölle wegen Grönland

Text Preview:
 USA vs. EU
Uneinigkeit in der EU über Reaktion auf Trumps Strafzölle wegen Grönland
In der EU herrscht offenbar Uneinigkeit darüber, wie man auf die Strafzölle von Trump wegen Grönland reagieren soll. Darauf deutet das bisherige demonstrative Schweigen fast aller nicht von den Strafzöllen betroffener EU-Staaten hin.
von Anti-Spiegel
20. Januar 2026 06:00 Uhr
In meinem ersten Artikel über Trumps Strafzölle gegen die europäischen Länder, die Dänemark in der Grönland-Frage gegen die USA unterstützen, habe ich bereits darauf hingewiesen, dass diese Geschichte schwerwiegende Folgen für die EU haben könnte. Der Grund ist, dass Trump Strafzölle gegen sechs EU-Länder verhängt hat, die nun Solidarität der gesamten EU einfordern, wobei jedoch 21 Länder bei der Geschichte nicht mitgemacht haben und sich teilweise offen skeptisch dazu geäußert haben. Sollte die EU harte Maßnahmen gegen die USA vorschlagen, könnte das bei den 21 Ländern auf Widerstand stoßen, die wegen Grönland nicht in einen Hande

--- Article ---
Title: Daily Telegraph veröffentlicht europäischen Plan für Sicherheitsgarantien für die Ukraine

Text Preview:
 Ukraine-Verhandlungen
Daily Telegraph veröffentlicht europäischen Plan für Sicherheitsgarantien für die Ukraine
Die britische Zeitung Daily Telegraph hat unter Berufung auf Quellen den möglichen Plan der Europäer für Sicherheitsgarantien für die Ukraine nach einem Waffenstillstand veröffentlicht.
von Anti-Spiegel
31. August 2025 15:12 Uhr
Da die russische Nachrichtenagentur TASS eine sehr gute Zusammenfassung des Artikels des Daily Telefraph veröffentlicht hat, verzichte ich darauf, das Rad neu zu erfinden und eine eigene Zusammenfassung zu schreiben. Daher übersetze die Zusammenfassung der TASS.
Beginn der Übersetzung:
Telegraph veröffentlicht europäischen Plan für Sicherheitsgarantien für die Ukraine
Dem Plan zufolge werden ukrainische Truppen die befestigte Grenze an der Frontlinie schützen, wie es in jedem Friedensabkommen vorgesehen ist.
Die endgültigen Details des Plans der europäischen Länder zur Gewährleistung der Sicherheit der Ukraine könnten noch an diesem Wochenende bekannt

--- Article ---
Title: Ukrainische Kamikazedrohne über Estland abgestürzt

Text Preview:
 Offiziell bestätigt
Ukrainische Kamikazedrohne über Estland abgestürzt
Litauische Medien bestätigen, dass eine ukrainische Kamikazedrohne in Estland abgestürzt ist. Datum und Uhrzeit stimmen mit dem Angriff auf eine russische Raffinerie überein, der am letzten Sonntag stattfand. Wie tief sind die Baltenstaaten in die Angriffe auf Russland verstrickt?
von Anti-Spiegel
31. August 2025 11:00 Uhr
Über den Drohnenangriff auf die Raffinerie im russischen Ust Luga nahe der estnischen Grenze und nicht weit von der russischen Millionenstadt St. Petersburg vom letzten Sonntag habe ich bereits berichtet. In dem Artikel habe ich auch die Frage aufgeworfen, ob die Drohnen, die den Großraum St. Petersburg angreifen, aus dem Baltikum kommen. Den Verdacht, dass die baltischen Staaten etwas mit dem Beschuss von Zielen im Nordwesten Russlands zu tun haben, hat bereits Anfang Juli ein einflussreicher russischer Abgeordneter geäußert und mit militärischen Konsequenzen gedroht, sollte sich das bestätigen.


--- Article ---
Title: Auch transatlantische US-Thinktanks geben die Ukraine verloren

Text Preview:
 US-Analyse
Auch transatlantische US-Thinktanks geben die Ukraine verloren
Das Council on Foreign Relations hat ein Kurzinterview mit einem seiner Russland-Experten veröffentlicht, das zwischen Zeilen empfiehlt, die Ukraine aufzugeben und sich den russischen Forderungen weitgehend zu beugen.
von Anti-Spiegel
1. September 2025 13:00 Uhr
Das Concil on Foreign Relations ist einer der mächtigsten Thinktanks der USA und schreibt regelrecht die US-Außenpolitik. Es ist streng transatlantisch ausgerichtet und nicht Trump-freundlich. Daher ist das Kurzinterview mit einem Russland-Experten, das das Council nun veröffentlicht hat, sehr bemerkenswert, denn darin fehlen die dort sonst üblichen Forderungen nach einer strategischen Niederlage Russlands.
Stattdessen hat der Experte eine ausgesprochen realistische Analyse der Situation gezeigt und auch die Lage und Stimmung in Russland korrekt wiedergegeben, auch wenn natürlich Hinweise wie „Meinungsumfragen in einem autoritären Staat wie Russland“ müss

================================================================================
Source: apollo
================================================================================

--- Article ---
Title: Deutschlandfahne auf Parkbank gemalt – Stadt kündigt aufwändiges Reinigungs-Verfahren an

Text Preview:
 Im niedersächsischen Helmstedt, an der Grenze zu Sachsen-Anhalt, haben Unbekannte mehrere Bänke auf dem Hügel am Ludgeriteich in Schwarz, Rot oder Gold angemalt. Dabei haben sie jede einzelne der drei Bohlen der Rückenlehne mit je einer der drei Farben der Nationalflagge bemalt, sodass die deutsche Nationalfahne zu sehen ist. Wie die Stadt Helmstedt Ende August mitteilte, bemängelte eine „besorgte Bürgerin“ das Anstreichen der Parkbänke im Rahmen des Forums Bürgeranliegen. Die Stadt hat sich daraufhin dem Problem angenommen.

Für den zuständigen Stadthof der 25.000 Einwohner starken Stadt stellt sich die Entfernung der Farbe nach eigenen Angaben als sehr aufwändig dar. So geht der Stadthof davon aus, dass die Bohlen abgebaut werden müssen, damit die Farbe abgehobelt werden kann. Da die Bemalung der Bohlen nicht mit verfassungsfeindlichen Symbolen, sondern lediglich mit der Deutschlandfahne erfolgte und die Farbe nicht abfärbt, sieht der Stadthof keine Eile und möchte die Arbeiten in de

--- Article ---
Title: Drei Gewalttaten in zwei Tagen – Messerangriff und Massenschlägereien auf der Sonnenallee

Text Preview:
 Auf der Sonnenallee in Berlin-Neukölln hat es innerhalb von zwei Tagen zwei schwere Gewalttaten gegeben. Am Freitagabend wurde ein 26-Jähriger bei einem Schlichtungsversuch mit einem Messer verletzt, am Vortag waren zwei Männer nach einer Auseinandersetzung über den Nahost-Konflikt von einer großen Gruppe angegriffen worden.

Nach Angaben der Polizei gerieten am Freitag gegen 17.20 Uhr zwei Gruppen vor einem Friseurladen in Streit. Zwei Männer im Alter von 26 und 27 Jahren versuchten, die Situation zu beruhigen. Aus einer der Gruppen trat daraufhin ein Mann hervor und stach dem 26-Jährigen ins Bein. Das Opfer kam mit einer Stichverletzung im Oberschenkel in ein Krankenhaus. Eine Festnahme erfolgte zunächst nicht, die Polizei ermittelt zu den Hintergründen.

Delivered by AMA

Bereits am Donnerstag hatte es an der Sonnenallee Ecke Hobrechtstraße einen weiteren Vorfall gegeben. Zwei Männer im Alter von 20 und 23 Jahren wurden dort laut Polizei von einer Gruppe von 30 bis 40 Personen attac

--- Article ---
Title: Wie sich Hamburg mit dem „Zukunftsentscheid“ in den Niedergang wählt

Text Preview:
 Der „Hamburger Zukunftsentscheid“ ist entschieden: Mit 53,2 Prozent Ja-Stimmen votierten die Bürger der Hansestadt für eine Verschärfung der Klimaziele. Nach dem vorläufigen amtlichen Ergebnis des Statistischen Amts für Hamburg und Schleswig-Holstein beteiligten sich 43,7 Prozent der Wahlberechtigten an der Abstimmung, rund 80 Prozent davon per Briefwahl. Letztlich stimmten also nur knapp 23 Prozent der Hamburger für eine strengere Klimapolitik.

Doch die weitreichenden Folgen dieser rein symbolpolitischen Entscheidung wird in den kommenden Jahren die gesamte Stadt tragen müssen: Weil die gemeinsame Initiative aus dem Umfeld von „Fridays for Future“, NABU und Verdi das notwendige Quorum von gerade einmal 20 Prozent der Wahlberechtigten erreicht hat, kann eine politisch engagierte Minderheit künftig ganz Hamburg den eigenen klimapolitischen Vorstellungen untertan machen – mitsamt allen zu erwartenden unbeabsichtigten Nebenwirkungen dieser Rosskur.

Delivered by AMA

Der Senat, der an da

--- Article ---
Title: Nach Terroranschlag: Australiens Regierung will Hunderttausende Waffen zurückkaufen, um Gewalt zu verhindern

Text Preview:
 Nach dem gezielten Angriff auf Juden am Strand von Bondi Beach hat die australische Regierung angekündigt, ein Rückkaufprogramm für Waffen zu starten. Bei dem Terroranschlag hatten der 24‑jährige Naveed Akram und sein Vater Sajid auf Juden geschossen, die am Sonntag am Strand versammelt waren, um Chanukka zu feiern. 15 Menschen wurden getötet, darunter ein zehnjähriges Mädchen. Über 40 Personen wurden verletzt. Der Täter Sajid Akram wurde von der Polizei erschossen, sein Sohn liegt verletzt im Krankenhaus. Er wurde wegen 15‑fachen Mordes angeklagt.

Sajid Akram besaß legal sechs Waffen, von denen einige für den Anschlag verwendet wurden. Das nahm die Regierung zum Anlass, um ein Rückkaufprogramm einzuleiten. „Die schrecklichen Vorgänge in Bondi zeigen, dass wir die Waffen von unseren Straßen verbannen müssen“, sagte Premierminister Anthony Albanese am Freitag auf einer Pressekonferenz. Er verwies darauf, dass der Täter in einem Vorort von Sydney lebte: „Es gibt keinen Grund, warum jema

--- Article ---
Title: „Sperrt die Männer weg“ – Grüne-Jugend-Chefin provoziert auf Instagram

Text Preview:
 „Sperrt die Männer weg“ – zu dieser Zeile tanzt die Bundessprecherin der Grünen Jugend, Henriette Held, in einem Video, dass sie 10. Januar auf Instagram veröffentlicht hat. Der Clip zeigt Held gemeinsam mit weiteren Mitgliedern der Nachwuchsorganisation. Zu dem Beitrag schrieb Held den Kommentar „Alles gesagt“.

Der verwendete Sound stammt aus dem Song „IDGAF“ der Rapperin Ikkimel. In dem Lied folgen auf die im Video verwendete Textzeile weitere, deutlich drastischer formulierte Passagen, darunter „sonst werden sie umgeklatscht“.

Werbung

Held steht seit Oktober 2025 an der Spitze der Grünen Jugend. Sie wurde auf dem Bundeskongress der Nachwuchsorganisation gemeinsam mit Luis Bobga zur neuen Doppelspitze gewählt. Beide folgten auf Jette Nietzard und Timon Dzienus.

Der Instagram-Post von Held ist nicht die erste Kontroverse um die neue Führung der Grünen Jugend. Bobga hatte kurz nach seinem Amtsantritt mit einem eigenen Social-Media-Video Kritik ausgelöst, in dem er den bayerischen

================================================================================
Source: Compact
================================================================================

--- Article ---
Title: Trotz Antifa: Wie die AfD im Westen weiter wächst

Text Preview:
 COMPACT-TV zu Besuch in Westdeutschlands AfD-Hochburg! Warum ist die blaue Partei ausgerechnet hier so stark? Und wie hält sie den Gegenwind von Antifa und Landesregierung aus? Wir treffen Land und Leute.

▶️ Unsere Reportage sehen Sie in dem Video oben.

COMPACT-TV ist für Sie gratis! Bitte spenden Sie zu unserer Unterstützung unter compact-online.de/unterstuetzen.

--- Article ---
Title: Merz kann es nicht

Text Preview:
 Zitat des Tages: „Jeder, der es gut mit der Union und dieser Regierung meint, ist jede Woche aufs Neue erstaunt und entsetzt über die Fettnapfquote.“ (Dennis Radtke, Bundesvorsitzender der Christlich-Demokratischen Arbeitnehmerschaft, Süddeutsche Zeitung)

„Merz, der sich als Hoffnungsträger der CDU präsentieren will, entpuppt sich als Teil des Problems: ein abgehobener Politiker, der die Sorgen der Menschen nicht versteht und mit den Interessen der Eliten verwoben ist.“ (COMPACT-Spezial „Die Altparteien“)

--- Article ---
Title: Widerspruch gegen Merz-Kriegskurs

Text Preview:
 Die Merz-Regierung setzt ziemlich ungeniert auf die Umsetzung der berüchtigten „Kriegstüchtigkeit“-Ansage von Verteidigungsminister Pistorius. Wir wollen uns nicht an diese Rhetorik gewöhnen, sondern setzen auf Frieden. Als Bekenntnis besonders geeignet: Die Druschba-Silbermedaille von COMPACT. Hier mehr erfahren.

Bundeskanzler Friedrich Merz forciert eine massive Aufrüstung der Bundeswehr und drängt beispielsweise, wie zuletzt beim Tag der Deutschen Industrie, auf eine Vervielfachung der Reservisten von derzeit 34.000 auf 200.000. „Unternehmen sollen ihre Mitarbeiter für den Reservisten-Dienst freistellen“, so Merz.

Erfreuliches Zögern

Wirtschaftsverbände wie der Bundesverband Mittelständische Wirtschaft (BVMW) begrüßen den Vorschlag brav, betonen jedoch, dass die Teilnahme freiwillig bleiben müsse. Viele Betriebe zögern  allerdings erfreulicherweise, da sie mit administrativen Hürden und Unklarheiten, etwa zur Lohnfortzahlung, konfrontiert sind.

Was sie offenbar weniger erkennen:

--- Article ---
Title: Von wegen Friedenskanzler! Mogelpackung Merz

Text Preview:
 In welch einer Parallelwelt die CDU mittlerweile angekommen ist, hat der Landesparteitag in Niedersachsen unterstrichen. Man gibt sich zufrieden und sieht in Friedrich Merz einen „Friedenskanzler“. Geht’s noch?! Wer wirklich Frieden will, der setzt auf Freundschaft mit Russland. Genau dafür steht unsere Druschba-Medaille in Silber. Hier mehr erfahren.

Am Wochenende hatte Friedrich Merz zur Abwechslung einen innenpolitischen Termin wahrzunehmen. Er war Gast auf dem Parteitag seiner CDU in Niedersachsen. Der Empfang fiel allerdings nur verhalten begeistert aus. Die neuesten Umfragen drücken offenbar aufs Gemüt der Parteigänger. Zuletzt hatte die AfD auch bei den Meinungsforschern von Insa zur Union aufgeschlossen, bei Forsa liegen die Blauen seit einigen Wochen bereits vorn.

Migration: Merz punktet kaum

Warum das so ist und weshalb auch die persönlichen Umfragewerte des Kanzlers sich im Sinkflug befinden, konnte man bei besagtem Parteitag in Osnabrück recht gut ablesen. In seiner Rede

--- Article ---
Title: Alles „Nazi“: VS warnt vor Auto-Kennzeichen

Text Preview:
 Der Verfassungsschutz ist einer großen Sache auf der Spur: Rechtsextremen Auto-Kennzeichen. Um dagegen vorzugehen, gibt es jetzt eine Handreichung. Kein Wunder, dass die AfD für diesen Unsinn nur Spott übrig hat. Die beste Antwort auf den Geheimdienst-Quatsch: Ein klares Bekenntnis zur bluaen Partei. Zum Beispiel mit unserem Höcke-Taler aus feinstem Silber. Sie haben das gute Stück noch nicht? Hier mehr erfahren.

Der Brandenburger Verfassungsschutz hat – natürlich vom Steuerzahler finanziert – ein „Informationsblatt“ an alle Zulassungsstellen des Landes ausgesandt, das vor „Codes der rechtsextremistisches Szene“ warnt, die bei Kennzeichen zukünftig nicht mehr vergeben werden dürften. Neben Kombinationen wie „SS“ oder „SA“, deren NS-Bezug sich aus dem geschichtlichen Kontext ergibt, wenngleich ein Steffen Schmidt oder eine Susanne Anton ihre Initialen dadurch nicht auf einem Kennzeichen tragen dürfen, treibt der Rechtsextremismus-Wahn der Behörde jedoch durchaus absurde Blüten.

So wir

================================================================================
Source: deusch_pravda
================================================================================

--- Article ---
Title: In Polen wollten sie den Organisator des Terroranschlags «Nordströme» heimlich belohnen

Text Preview:
 nan

--- Article ---
Title: 80. Jahrestag der Nürnberger Prozesse

Text Preview:
 nan

--- Article ---
Title: „Alles ist sehr schlecht.“ Ein General der ukrainischen Streitkräfte macht eine unerwartete Aussage

Text Preview:
 „Alles ist sehr schlecht.“ Ein General der ukrainischen Streitkräfte macht eine unerwartete Aussage
Kiew wird weiterhin Gebiete verlieren, sagte der pensionierte Generalmajor der ukrainischen Streitkräfte Dmitrij Marchenko im
Gespräch mit „Strana“.
Seiner Meinung nach seien die militärische Führung und die Einstellung zum Konflikt schuld daran. Wenn sich nichts ändere, würden bald Cherson und Nikolaev von der Ukraine abfallen.
„Die Lage ist sehr angespannt. Die Stimmung der Menschen ist ohnehin schlecht, ich möchte sie nicht noch weiter verschlechtern, aber ich sage, dass alles sehr schlecht ist,“ fasste Marchenko zusammen.
@ukr_leaks_de

--- Article ---
Title: ️Spahn nennt Vorwürfe zur Maskenbeschaffung bösartig

Text Preview:
 ️
Spahn nennt Vorwürfe zur Maskenbeschaffung bösartig
Unionsfraktionschef Jens #Spahn (CDU) steht wegen der Maskenbeschaffung während der #Coronapandemie weiter in der Kritik. Einem möglichen Untersuchungsausschuss sieht er nach eigenen Worten gelassen entgegen. Er habe keine Angst vor den Fragen eines solchen Ausschusses, sagte der ehemalige Bundesgesundheitsminister dem „Stern“. Eine Enquete-Kommission sei aber der bessere Weg zur Aufarbeitung und gesellschaftlichen Befriedung.
Die Coronapandemie müsse aufgearbeitet werden, sagte Spahn. Er beklagte bösartige Vorwürfe in der Debatte um seine Person.
"Ich wünsche mir, dass mein Handeln im Kontext der damaligen Notlage bewertet wird. Wir waren völlig unvorbereitet", sagte er.
Abonniert
@satellit_de
!

--- Article ---
Title: Kommentar von Kirill Dmitriev zu den Verhandlungen über die Ukraine in Miami

Text Preview:
 Kommentar von Kirill Dmitriev zu den Verhandlungen über die Ukraine in Miami.
Video: Denis Solovych/TASS
Abonnieren Sie TASS / Die Welt bei Max

================================================================================
Source: Nius_Rohdaten_neu
================================================================================

--- Article ---
Title: TK-Chef kritisiert Klingbeil: „Versicherte und Arbeitgeber müssen jedes Jahr 10 Milliarden für die Versicherung von Bürgergeld-Empfängern aufbringen“

Text Preview:
 # TK-Chef kritisiert Klingbeil: „Versicherte und Arbeitgeber müssen jedes Jahr 10 Milliarden für die Versicherung von Bürgergeld-Empfängern aufbringen“

Jens Baas, Vorstandsvorsitzender der größten deutschen Krankenkasse, der Techniker Krankenkasse (TK), hat die Bundesregierung scharf kritisiert.
„Da isst man nichts Böses ahnend sein Sonntagsfrühstück und geht durch die Morgenpresse, und schon bleibt einem das Brötchen im Hals stecken“, leitet Baas seinen Wut-Post ein, den er am Sonntag auf dem Portal LinkedIn veröffentlichte.
Der Grund für Baas' Ärger: Die gesetzlichen Krankenkassen in Deutschland steuern auf ein riesiges Finanzloch zu. Für 2026 wird ein Defizit von etwa vier Milliarden Euro erwartet, das 2027 auf rund 12 Milliarden Euro steigen könnte. Um diese Lücke zu schließen, prognostiziert der GKV-Spitzenverband eine Erhöhung des durchschnittlichen Zusatzbeitrags von derzeit 17,5 Prozent auf 18,3 Prozent.
Berichterstattung der Bild darüber, dass weder Gesundheitsministerin Nina

--- Article ---
Title: Kein Volk, kein Ort, kein Land: Warum die Politik nicht mehr von „Deutschen“ spricht, sondern von der „Bevölkerung“

Text Preview:
 # Kein Volk, kein Ort, kein Land: Warum die Politik nicht mehr von „Deutschen“ spricht, sondern von der „Bevölkerung“


In [121]:
# Zeige das DataFrame für Russia Today (RT_de)
if "RT_de" in dfs_by_source:
    rt_df = dfs_by_source["RT_de"]
elif "df_rt" in globals():
    rt_df = df_rt
else:
    raise KeyError("RT_de nicht gefunden (weder in dfs_by_source noch als df_rt)")

print("RT_de shape:", rt_df.shape)
display(rt_df)

RT_de shape: (12390, 9)

             Date                        Category  \
0      2026-01-19    Hauptseite\n/\nInternational
1      2026-01-19    Hauptseite\n/\nInternational
2      2026-01-19  Hauptseite\n/\nNahost-Konflikt
3      2026-01-19          Hauptseite\n/\nSchweiz
4      2026-01-19    Hauptseite\n/\nInternational
...           ...                             ...
12385  2024-11-14          Hauptseite\n/\nSchweiz
12386  2024-11-14    Hauptseite\n/\nUkraine-Krieg
12387  2024-11-14       Hauptseite\n/\nÖsterreich
12388  2024-11-14      Hauptseite\n/\nDeutschland
12389  2024-11-14      Hauptseite\n/\nDeutschland

                                                                                                   Title  \
0                                Trump: Dänemark kann "russische Bedrohung" in Grönland nicht beseitigen
1                                                  Mindestens 39 Tote bei schwerem Zugunglück in Spanien
2              Syriens Machthaber al-Scharaa verschiebt wegen Militäroperationen seinen Termin in Berlin
3                            Davos wird zum US-Forum: Zum Auftakt steht das WEF im Zeichen Donald Trumps
4      Welch erbärmliche und prinzipienlose Kreaturen: Warum die Europäer nun Schutz bei Russland suchen
...                                                                                                  ...
12385                            Gedemütigt und geschlagen: Was Prostituierte in der Schweiz durchmachen
12386                                    Bloomberg: Ukrainer spenden immer weniger für ihre Streitkräfte
12387                                                Österreich: Traditionsmarke Kika/Leiner vor dem Aus
12388                                                 Sachsen: CDU und SPD wollen jetzt allein koalieren
12389                            Falls Mützenich Außenminister wird: Andrei Melnyk kündigt Selbstmord an

                                                                                                                                                                                                                                                                                                                                                                 Summary  \
0                                                                                                           Die Nordatlantikallianz habe Dänemark 20 Jahre lang gebeten, die "russische Bedrohung" für Grönland zu beseitigen, aber Kopenhagen habe diese Aufgabe nicht bewältigt, schrieb US-Präsident Donald Trump. Jetzt sei es "an der Zeit", diese Frage zu klären.
1                                                                                                      Bei einem schweren Zugunglück nahe Córdoba entgleisten und kollidierten zwei Hochgeschwindigkeitszüge. Mindestens 39 Menschen kamen ums Leben, rund 70 wurden verletzt. Die Ursache ist unklar. Der Bahnverkehr zwischen Madrid und Andalusien bleibt ausgesetzt.
2                      Der für Anfang der Woche angekündigte Besuch des syrischen Übergangspräsidenten Ahmed al-Scharaa im Berliner Kanzleramt ist seitens Damaskus abgesagt worden. Grund seien die militärischen Ereignisse im Nordosten des Landes. Syrische Medien haben bekannt gegeben, dass mit den kurdischen SDF-Kräften ein Waffenstillstand vereinbart wurde.
3                                                                                                                                                  Die größte US-Delegation aller Zeiten, massive Sicherheitsvorkehrungen und konkrete Machtpolitik machen Davos zur Bühne amerikanischer Interessen. Noch vor der Eröffnung steht fest: Dieses WEF gehört Donald Trump.
4                                                                       Europa hat Russlands Rolle verkannt und zahlt nun den Preis, während Washington das Völkerrecht und die UNO offen entwertet. Der geplante "Friedensrat" der USA verstärkt die Angst vor einer neuen, machtbasierten Weltordnung. Russland wird damit zum Hüter geltender internationaler Regeln.
...                                                                                                                                                                                                                                                                                                                                                                  ...
12385                                                                                                                                                                                  Die Realität von Sexarbeiterinnen in der Schweiz bleibt auch heute noch erschreckend: Gewalt, Diskriminierung und sexuelle Übergriffe gehören zum Alltag vieler Frauen im Milieu.
12386                                                                                              Ukrainische Stiftungen, die die Armee unterstützen, melden starke Rückgänge der Spenden. Angesichts der wirtschaftlichen Schwierigkeiten, Kriegsmüdigkeit und Donald Trumps Wahlsieg ist die Bereitschaft der Ukrainer, zur Verteidigung beizutragen, zurückgegangen.
12387  Ein bitteres Ende für den österreichischen Möbelhandel: Die österreichische Möbelkette Kika/Leiner steht kurz vor der Einbringung eines Insolvenzantrags, was für die Kunden und die 1.350 Beschäftigten eine ungewisse Zukunft mit sich bringt. Experten rechnen mit einer Liquidation, während Konsumentenschützer zur raschen Einlösung von Gutscheinen raten.
12388                                                                                                Am 1. September waren die Landtagswahlen in Sachsen, aber noch steht keine neue Regierung. Jetzt soll es also eine Koalition aus CDU und SPD richten. Es ist allerdings noch nicht klar, um welchen Preis. Die beiden Parteien erreichen keine Mehrheit im Landtag.
12389                                                                                   Der Ex-Botschafter der Ukraine in Deutschland Andrei Melnyk steht mit SPD-Fraktionschef Rolf Mützenich schon seit Längerem auf Kriegsfuß. Nun kündigte Melnyk gar seinen Selbstmord an, sollte Mützenich in der nächsten Bundesregierung den Posten des Außenministers besetzen.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Text  \

In [122]:
# RT today sample article + link to click

from IPython.display import HTML
from html import escape

pd.set_option("display.max_colwidth", None)

# get RT_de frame
if "RT_de" in dfs_by_source:
    rt = dfs_by_source["RT_de"]
elif "rt_df" in globals():
    rt = rt_df
else:
    raise KeyError("RT_de not found in dfs_by_source or as rt_df")

cols_map = {c.lower(): c for c in rt.columns}
full_col = cols_map.get("full_text") or cols_map.get("text") or cols_map.get("fulltext")
url_col  = cols_map.get("url") or cols_map.get("link")

if not full_col or not url_col:
    raise KeyError(f"Could not find text/url columns in RT_de. Available columns: {list(rt.columns)}")

sample_df = rt[[full_col, url_col]].sample(5, random_state=42).reset_index(drop=True)

def format_text(t):
    t = escape(str(t)).replace("\n", "<br>")
    return "<div style='max-width:1200px;white-space:normal;overflow:auto'>" + t + "</div>"

sample_df["full_text"] = sample_df[full_col].apply(format_text)
sample_df["url"] = sample_df[url_col].astype(str).apply(
    lambda u: f'<a href="{escape(u)}" target="_blank" rel="noopener noreferrer">{escape(u)}</a>'
)

html = sample_df[["full_text", "url"]].to_html(escape=False, index=False)
display(HTML(html))

## Topic Modelling (RT_de) — Preprocessing & Rationale

**Data input (RT_de)**
- Dataframe: `rt_topic_df` from `dfs_by_source["RT_de"]` (fallback: `rt_df`).
- Columns used (explicit): `Full_Text` for text and `Date` for timestamps.

**Why minimal preprocessing here?**
- `Full_Text` is already relatively clean, so we keep preprocessing simple and focused on stopword removal for better topic quality.

**Cleaning steps**
1. Copy raw model text into `topic_text_raw` (source columns are not overwritten).
2. Minimal normalization: lowercasing, URL removal, whitespace normalization.
3. Stopword removal: spaCy German stopwords (`spacy.lang.de.stop_words.STOP_WORDS`) + short custom list (`rt`, `https`, `http`, `www`, `de`, `freedert`, `online`).
4. Token filtering: remove numeric-only tokens and very short tokens (`< 2` chars).

**Chunking strategy (implemented)**
- We chunk each cleaned article into fixed token windows before BERTopic.
- Settings: `CHUNK_SIZE_TOKENS = 220`, `CHUNK_OVERLAP_TOKENS = 40`, `MIN_CHUNK_TOKENS = 40`.
- Why: long articles can dominate embeddings; chunking keeps topic signals more balanced and still preserves local context via overlap.

**Reproducibility notes**
- Deterministic rules and fixed embedding model: `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`.
- BERTopic settings fixed (`language="multilingual"`, `min_topic_size=25`, `calculate_probabilities=False`).
- Default uses full RT_de (`MAX_DOCS = None`); optional sampling uses `random_state=42`.

**Sanity checks**
- Print article/chunk counts and date range used for BERTopic.
- Show top tokens after cleaning to verify stopword removal worked (no `der/die/das` dominance).

In [123]:
%pip install spacy

Requirement already satisfied: spacy in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (2.4.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (80.10.2)
Requirement already satisfied: packaging>=20.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: wrapt in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.1)
Requirement already satisfied: click>=8.2.1 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (14.3.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/MattisHaumann/Dev/Thesis/.venv/lib/python3.11/site-packages (from jinja2->spacy) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [124]:
# BERTopic auf RT_de (clean + reproducible)
# Optional one-time install (if needed):
# %pip install bertopic sentence-transformers umap-learn hdbscan huggingface_hub spacy

import os
import re
from collections import Counter

import pandas as pd

try:
    from bertopic import BERTopic
except ImportError as e:
    raise ImportError(
        "BERTopic not installed. Run: %pip install bertopic sentence-transformers umap-learn hdbscan"
    ) from e

# Optional HF auth via environment only (no interactive prompt)
hf_token = os.getenv('HF_TOKEN')
if hf_token:
    try:
        from huggingface_hub import login
        login(token=hf_token, add_to_git_credential=False, skip_if_logged_in=True)
        print('Hugging Face login via HF_TOKEN: active')
    except Exception as e:
        print(f'Hugging Face login skipped: {e}')
else:
    print('HF_TOKEN not set. Continuing without explicit HF login.')

# 1) Get RT_de dataframe from existing EDA objects
if 'RT_de' in dfs_by_source:
    rt_topic_df = dfs_by_source['RT_de'].copy()
elif 'rt_df' in globals():
    rt_topic_df = rt_df.copy()
else:
    raise KeyError('RT_de not found in dfs_by_source or rt_df')

# 2) Use explicit RT_de columns from your schema
required_cols = {'Full_Text', 'Date'}
missing_cols = required_cols.difference(rt_topic_df.columns)
if missing_cols:
    raise KeyError(f'Missing required RT_de columns: {sorted(missing_cols)}')

# 3) Create topic-modelling columns (keep original columns unchanged)
rt_topic_df['topic_text_raw'] = rt_topic_df['Full_Text'].astype(str)
rt_topic_df['topic_date'] = pd.to_datetime(rt_topic_df['Date'], errors='coerce')

# 4) Stopwords: spaCy German stopwords + short custom additions
try:
    from spacy.lang.de.stop_words import STOP_WORDS
except ImportError as e:
    raise ImportError(
        "spaCy German stopwords are required. Run: %pip install spacy"
    ) from e

german_stopwords = set(STOP_WORDS)
custom_stopwords = {'rt', 'https', 'http', 'www', 'de', 'freedert', 'online'}
all_stopwords = german_stopwords.union(custom_stopwords)

url_pattern = re.compile(r'https?://\S+|www\.\S+', flags=re.IGNORECASE)
token_pattern = re.compile(r'[^\W_]+', flags=re.UNICODE)

def clean_topic_text(text: str) -> str:
    # Minimal cleaning: keep content, mostly remove stopwords/noise
    text = str(text).lower()
    text = url_pattern.sub(' ', text)
    text = re.sub(r'\s+', ' ', text).strip()

    tokens = token_pattern.findall(text)
    kept = []
    for tok in tokens:
        if tok in all_stopwords:
            continue
        if tok.isnumeric():
            continue
        if len(tok) < 2:
            continue
        kept.append(tok)

    return ' '.join(kept)

rt_topic_df['topic_text_clean'] = rt_topic_df['topic_text_raw'].apply(clean_topic_text)

# 5) Chunking (implemented): split long cleaned texts into overlapping token windows
CHUNK_SIZE_TOKENS = 220
CHUNK_OVERLAP_TOKENS = 40
MIN_CHUNK_TOKENS = 40

if CHUNK_OVERLAP_TOKENS >= CHUNK_SIZE_TOKENS:
    raise ValueError('CHUNK_OVERLAP_TOKENS must be smaller than CHUNK_SIZE_TOKENS')

def chunk_text(text: str) -> list:
    tokens = str(text).split()
    if not tokens:
        return []

    step = CHUNK_SIZE_TOKENS - CHUNK_OVERLAP_TOKENS
    chunks = []
    for i in range(0, len(tokens), step):
        chunk_tokens = tokens[i:i + CHUNK_SIZE_TOKENS]
        if len(chunk_tokens) < MIN_CHUNK_TOKENS:
            continue
        chunks.append(' '.join(chunk_tokens))

    # If article is short but non-empty, keep one chunk
    if not chunks and len(tokens) > 0:
        chunks = [' '.join(tokens)]

    return chunks

rt_topic_df['topic_text_model'] = rt_topic_df['topic_text_clean']
rt_topic_df['topic_chunks'] = rt_topic_df['topic_text_model'].apply(chunk_text)

# Build chunk-level modelling frame for BERTopic
model_df = rt_topic_df[['topic_date', 'topic_chunks']].explode('topic_chunks').rename(columns={'topic_chunks': 'topic_text_model'})
model_df = model_df[
    model_df['topic_date'].notna()
    & model_df['topic_text_model'].notna()
    & model_df['topic_text_model'].str.len().gt(0)
].copy()

# Full RT_de by default; set MAX_DOCS for quick local tests only
MAX_DOCS = None
if MAX_DOCS is not None and len(model_df) > MAX_DOCS:
    model_df = model_df.sample(MAX_DOCS, random_state=42)

model_df = model_df.sort_values('topic_date').reset_index(drop=True)

if model_df.empty:
    raise ValueError('No usable RT_de chunks after preprocessing.')

docs = model_df['topic_text_model'].tolist()
timestamps = model_df['topic_date'].dt.to_pydatetime().tolist()

print(f'RT_de articles used: {rt_topic_df["topic_date"].notna().sum()}')
print(f'RT_de chunks used for BERTopic: {len(docs)}')
print(f'Date range: {model_df["topic_date"].min().date()} to {model_df["topic_date"].max().date()}')

# Sanity check: most frequent tokens after cleaning
token_counts = Counter(' '.join(rt_topic_df['topic_text_clean']).split())
top_tokens_df = pd.DataFrame(token_counts.most_common(20), columns=['token', 'count'])
display(top_tokens_df)

# 6) BERTopic configuration (stable + reproducible)
topic_model = BERTopic(
    language='multilingual',
    embedding_model='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
    min_topic_size=25,
    calculate_probabilities=False,
    verbose=True,
)

topics, _ = topic_model.fit_transform(docs)
topic_info = topic_model.get_topic_info()

display(topic_info.head(20))
display(topic_model.visualize_barchart(top_n_topics=12))

HF_TOKEN not set. Continuing without explicit HF login.
RT_de articles used: 12390
RT_de chunks used for BERTopic: 25347
Date range: 2024-11-14 to 2026-01-19

           token  count
0        ukraine  28094
1             us  27029
2       russland  26916
3          trump  20534
4            usa  18611
5             eu  17386
6     russischen  14843
7          thema  14147
8        prozent  11785
9      präsident  10992
10   deutschland  10382
11     russische  10378
12          nato   8534
13     regierung   8044
14  ukrainischen   7951
15         putin   7897
16        moskau   7860
17          laut   7632
18      erklärte   7409
19        europa   7353

2026-02-19 19:56:03,398 - BERTopic - Embedding - Transforming documents to embeddings.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/793 [00:00<?, ?it/s]

2026-02-19 19:58:09,645 - BERTopic - Embedding - Completed ✓
2026-02-19 19:58:09,646 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-19 19:58:12,763 - BERTopic - Dimensionality - Completed ✓
2026-02-19 19:58:12,765 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-19 19:58:15,201 - BERTopic - Cluster - Completed ✓
2026-02-19 19:58:15,207 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-19 19:58:17,351 - BERTopic - Representation - Completed ✓

    Topic  Count                                                Name  \
0      -1  12496                           -1_ukraine_russland_eu_us
1       0   1147                               0_afd_spd_cdu_prozent
2       1    847                     1_putin_ukraine_trump_präsident
3       2    761                    2_israel_hamas_gaza_gazastreifen
4       3    666                           3_venezuela_maduro_us_usa
5       4    627                4_afd_deutschen_deutschland_deutsche
6       5    596         5_selenskij_ukraine_selenskijs_ukrainischen
7       6    459                             6_trump_musk_us_epstein
8       7    452                 7_prozent_euro_deutschland_deutsche
9       8    373                    8_china_chinesische_peking_zölle
10      9    332          9_streitkräfte_ukrainischen_truppen_gebiet
11     10    274                 10_europa_russland_europäischen_usa
12     11    264  11_vermögenswerte_unternehmen_russischen_euroclear
13     12    260            12_sanktionen_russland_eu_sanktionspaket
14     13    234                       13_gas_gazprom_lng_kubikmeter
15     14    234                     14_ukraine_milliarden_eu_dollar
16     15    232              15_raketen_oreschnik_rakete_reichweite
17     16    212                        16_corona_covid_who_pandemie
18     17    195                     17_schiff_ostsee_schiffe_tanker
19     18    182                      18_polizei_verletzt_täter_mann

                                                                                                  Representation  \
0                              [ukraine, russland, eu, us, russischen, deutschland, usa, nato, thema, russische]
1                                           [afd, spd, cdu, prozent, bsw, partei, grünen, habeck, fpö, parteien]
2                       [putin, ukraine, trump, präsident, russland, treffen, moskau, wladimir, präsidenten, us]
3     [israel, hamas, gaza, gazastreifen, israelischen, netanjahu, israels, israelische, geiseln, palästinenser]
4             [venezuela, maduro, us, usa, venezuelas, venezolanischen, trump, karibik, venezolanische, caracas]
5                              [afd, deutschen, deutschland, deutsche, berlin, krieg, russland, spd, cdu, thema]
6            [selenskij, ukraine, selenskijs, ukrainischen, wladimir, ukrainische, kiew, trump, präsident, nabu]
7                                 [trump, musk, us, epstein, trumps, donald, präsident, biden, elon, demokraten]
8        [prozent, euro, deutschland, deutsche, deutschen, wirtschaft, milliarden, merz, millionen, unternehmen]
9                                  [china, chinesische, peking, zölle, chinesischen, usa, xi, chinas, us, trump]
10      [streitkräfte, ukrainischen, truppen, gebiet, stadt, sumy, pokrowsk, podoljaka, ukrainische, russischen]
11                          [europa, russland, europäischen, usa, krieg, eu, nato, ukraine, russischen, staaten]
12  [vermögenswerte, unternehmen, russischen, euroclear, eu, milliarden, belgien, eingefrorenen, russland, euro]
13                [sanktionen, russland, eu, sanktionspaket, trump, us, moskau, russischen, verhängt, präsident]
14               [gas, gazprom, lng, kubikmeter, pipeline, eu, russischem, gaslieferungen, slowakei, russisches]
15                        [ukraine, milliarden, eu, dollar, euro, kiew, geld, us, vermögenswerte, unterstützung]
16        [raketen, oreschnik, rakete, reichweite, drohnen, systeme, burewestnik, einsatz, starlink, satelliten]
17                           [corona, covid, who, pandemie, mrna, impfstoffe, impfung, impfungen, epa, biontech]
18                  [schiff, ostsee, schiffe, tanker, marine, schattenflotte, flagge, nato, estland, finnischen]
19                       [polizei, verletzt, täter, mann, jährige, laut, messer, verletzte, magdeburg, jähriger]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Representative_Docs
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [us außenminister marco rubio ukraine konflikt beendet behauptung kiew könne moskau besiegen unehrlich außenminister usa laut marco rubio müsse schnell diplomatische lösung ukraine konflikt gefunden konfliktparteien müssten kompromisse außenminister ukraine kämpfe russland zerstört konflikt rasch verhandlungen beigelegt us außenminister marco rubio interview the megyn kelly show donnerstag bekräftigte rubio bereitschaft us präsident donald trump diplomatische lösung ukraine krise finden trump glaube konflikt beendet russisches verteidigungsministerium ukrainische soldaten desertiert verhandlung verhandlung seiten aufgeben rubio wachsende zahl demokraten vorherigen regierung us präsident joe biden versprochen kiew nötig unterstützen anerkennen finanziert pattsituation langwieriger konflikt schlimmer pattsituation ukraine schrittweise zerstört territorium verliert außenminister unehrlichkeit besteht menschen irgendwie gebracht glauben ukraine lage russland besiegen wissen zerstören weg zurückzudrängen welt aussah fügte rubio hinzu infolge konflikts ukraine hundert zurückgeworfen energienetz zerstört wissen ukrainer ukraine verlassen ländern leben zurückkehren zukunft hinsicht gefährdet warnte rubio analyse selenskij frieden braucht amtsantritt woche erklärte trump jederzeit bereit russischen präsidenten wladimir putin treffen diplomatische lösung ukraine konflikt finden kreml entgegnete putin ebenfalls gesprächen amerikanischen amtskollegen bereit betonte washington moskau herangetreten kontakte staatschefs organisieren russische präsident anfang woche usa sponsoren kiews einfachen weg gebe frieden erreichen finanzierung regierung ukrainischen präsidenten wladimir selenskij einstellen monat überleben geld sinne munition ausgeht monat anderthalb monaten erklärte putin thema mobilisierung ukraine jährigen dran, treffen selenskij europäischen staatschefs trump ruft putin andonald trump wladimir putin unmittelbar gesprächen selenskij europäischen staats regierungschefs anrufen äußerte us präsident treffen ukrainischen präsidenten wladimir selenskij weißen haus us präsident donald trump angekündigt russischer amtskollege wladimir putin anruf erwartet teilte republikaner treffen ukrainischen präsidenten wladimir selenskij gesprochen präsidenten erzählt indirekt präsident putin gesprochen unmittelbar heutigen treffen telefongespräch führen trump präzisierte indirekte dialog putin organisiert us staatschef betonte dreiertreffen beteiligung russland ukraine usa stattfinden fuhr fort treffen konfrontation weitergehen chance setzen wartet anruf treffen beendet selenskij trump führen verhandlungen weißen haus zuvor us präsident erklärt selenskij könne konflikt russland fast sofort beenden krim russisch anerkennt nato beitritt verzichtet warschau europa trumps position ukraine frage beeinflussen washington reisten präsidentin europäischen kommission ursula leyen generalsekretär nato mark rutte britische premierminister keir starmer französische präsident emmanuel macron deutsche bundeskanzler friedrich merz italienische ministerpräsidentin giorgia meloni finnische präsident alexander stubb zuletzt putin trump august alaska persönlich miteinander gesprochen erörterten möglichkeiten beilegung russisch ukrainischen konflikts verhandlungen alaska telefonierte russische präsident mehreren staatschefs präsidenten brasiliens kirgisistans weißrusslands usbekistans südafrikas tadschikistans kasachstans thema putins verhandlungsmasse beendigung krieges ukraine, moskau vertritt auffassung frieden erreicht ukraine neutralität entmilitarisierung entnazifizierung verpflichtet territorialen gegebenheiten ort anerkennt kiew bereit traum weltkrieg aufzugeben scholz erinnerte pressekonferenz deutschen steuerzahler tatsache klar bedeutet ukraine finanziell militärischen mitteln unterstützen wissen größten unterstützer usa deutschland deutschland milliarden euro unterstützung ukraine aufgebracht bleibt internationale transatlantische unterstützung ukraine wichtig sicherheit landes europas angaben kieler instituts weltwirtschaft ifw deutschland milliarden dollar militärischer sonstiger hilfe zweitgrößte staatliche einzelgeber scholz wies bedenken moskaus worten russischen perspektiven akzeptiert frage entmilitarisierung russland fordert akzeptiert zudem erklärte ukraine stark angegriffen frieden ukraine erreicht russland krieg beendet ukraine hilfe verlassen verteidigen starken armee funktionierenden sicherheitsarchitektur entscheidung ukraine ukraine pic twitter com ggek6fs4rs bundeskanzler olaf scholz bundeskanzler march deutsche bundeskanzler äußerte besorgt möglichkeit konfrontativen regierung kiew demokratische souveräne nation ukraine inakzeptabel hält wladimir selenskijs fünfjährige amtszeit präsident abgelaufen durchführung neuwahlen hinweis verhängte kriegsrecht abgelehnt us präsident donald trump diktator wahlen bezeichnet verabschiedeten ukrainischen gesetzgeber anlauf antrag ansprüche befugnisse präsidenten unterstützt längeren telefongespräch russischen präsidenten wladimir putin us amerikanischen amtskollegen donald trump monat signalisierte kreml bereitschaft friedensprozess einzuleiten betonte ursachen konflikts angegangen müssten moskau strikt nato truppen deckmantel friedenstruppen kiews bestrebungen block beizutreten sieht gründe eskalation konflikts anfang scholz stellte erklärung london fest dinge besprochen nächster nächste mal brüssel thema waltz deutet selenskij möglicherweise]

In [125]:
# Topics over time (RT_de)
topics_over_time = topic_model.topics_over_time(
    docs=docs,
    timestamps=timestamps,
    nr_bins=20,
)

display(topics_over_time.head(20))

display(topic_model.visualize_topics_over_time(
    topics_over_time,
    top_n_topics=10,
))

20it [00:45,  2.30s/it]

,Topic,Words,Frequency,Timestamp
0,-1,"ukraine, russland, nato, russischen, us",696,2024-11-13 13:39:21.600
1,0,"spd, bsw, afd, habeck, cdu",70,2024-11-13 13:39:21.600
2,1,"ukraine, putin, trump, russland, präsident",36,2024-11-13 13:39:21.600
3,2,"israel, israelischen, netanjahu, hamas, gaza",24,2024-11-13 13:39:21.600
4,3,"venezuela, peru, venezuelas, fentanyl, usa",6,2024-11-13 13:39:21.600
5,4,"krieg, deutschen, deutschland, deutsche, rothschild",33,2024-11-13 13:39:21.600
6,5,"selenskij, ukraine, selenskijs, trump, kiew",21,2024-11-13 13:39:21.600
7,6,"trump, biden, bhattacharya, us, hunter",15,2024-11-13 13:39:21.600
8,7,"prozent, deutschland, deutschen, ifo, euro",19,2024-11-13 13:39:21.600
9,8,"china, peking, chinesische, chinas, xi",27,2024-11-13 13:39:21.600
10,9,"kurachowo, streitkräfte, stadt, ukrainischen, truppen",24,2024-11-13 13:39:21.600
11,10,"russland, europa, russischen, ukraine, europäischen",18,2024-11-13 13:39:21.600
12,11,"twer, lindemann, larin, euro, vermögenswerte",3,2024-11-13 13:39:21.600
13,12,"sanktionen, gazprombank, russland, eu, verhängt",11,2024-11-13 13:39:21.600
14,13,"gazprom, omv, gas, gaslieferungen, österreichischen",9,2024-11-13 13:39:21.600
15,14,"ukraine, milliarden, spenden, lindner, pritula",9,2024-11-13 13:39:21.600
16,15,"oreschnik, raketen, rakete, reichweite, einsatz",38,2024-11-13 13:39:21.600
17,16,"corona, covid, pandemie, paxlovid, virus",23,2024-11-13 13:39:21.600
18,17,"ostsee, schiff, werft, sabotage, kabel",8,2024-11-13 13:39:21.600
19,18,"ecke, getötet, nähe, geschäfts, mann",1,2024-11-13 13:39:21.600

## Antispiegel — Topic Modelling (same pipeline as RT_de)

In [126]:
# Antispiegel topic modelling (same pipeline as RT_de)
# Uses the same cleaning, chunking, BERTopic setup, and outputs as RT_de.
if 'BERTopic' not in globals() or 'clean_topic_text' not in globals() or 'chunk_text' not in globals():
    raise RuntimeError('Please run the RT_de topic modelling cell first.')
antispiegel_source_key = next((k for k in dfs_by_source if k.lower() == 'antispiegel'), None)
if antispiegel_source_key is None:
    raise KeyError(f"Source not found for Antispiegel. Available sources: {list(dfs_by_source.keys())}")
antispiegel_topic_df = dfs_by_source[antispiegel_source_key].copy()
required_cols = {'Full Text', 'date'}
missing_cols = required_cols.difference(antispiegel_topic_df.columns)
if missing_cols:
    raise KeyError(f"Missing required columns for Antispiegel: {sorted(missing_cols)}")
# Keep only rows with available full text
antispiegel_topic_df = antispiegel_topic_df[antispiegel_topic_df['Full_Text'].notna()].copy()
# Same topic columns as RT_de
antispiegel_topic_df['topic_text_raw'] = antispiegel_topic_df['Full Text'].astype(str)
antispiegel_topic_df['topic_date'] = pd.to_datetime(antispiegel_topic_df['date'], errors='coerce')
# Same cleaning pipeline as RT_de
antispiegel_topic_df['topic_text_clean'] = antispiegel_topic_df['topic_text_raw'].apply(clean_topic_text)
antispiegel_topic_df['topic_text_model'] = antispiegel_topic_df['topic_text_clean']
# Same chunking pipeline as RT_de
antispiegel_topic_df['topic_chunks'] = antispiegel_topic_df['topic_text_model'].apply(chunk_text)
antispiegel_model_df = (
    antispiegel_topic_df[['topic_date', 'topic_chunks']]
    .explode('topic_chunks')
    .rename(columns={'topic_chunks': 'topic_text_model'})
)
antispiegel_model_df = antispiegel_model_df[
    antispiegel_model_df['topic_date'].notna()
    & antispiegel_model_df['topic_text_model'].notna()
    & antispiegel_model_df['topic_text_model'].str.len().gt(0)
].copy()
# Full corpus by default (no sampling)
MAX_DOCS = None
if MAX_DOCS is not None and len(antispiegel_model_df) > MAX_DOCS:
    antispiegel_model_df = antispiegel_model_df.sample(MAX_DOCS, random_state=42)
antispiegel_model_df = antispiegel_model_df.sort_values('topic_date').reset_index(drop=True)
if antispiegel_model_df.empty:
    raise ValueError('No usable chunks after preprocessing.')
antispiegel_docs = antispiegel_model_df['topic_text_model'].tolist()
antispiegel_timestamps = antispiegel_model_df['topic_date'].dt.to_pydatetime().tolist()
print(f'Antispiegel articles used: {antispiegel_topic_df["topic_date"].notna().sum()}')
print(f'Antispiegel chunks used for BERTopic: {len(antispiegel_docs)}')
print(f'Date range: {antispiegel_model_df["topic_date"].min().date()} to {antispiegel_model_df["topic_date"].max().date()}')
# Same sanity check as RT_de
antispiegel_token_counts = Counter(' '.join(antispiegel_topic_df['topic_text_clean']).split())
antispiegel_top_tokens_df = pd.DataFrame(antispiegel_token_counts.most_common(20), columns=['token', 'count'])
# Overall non-time topic overview (all documents/chunks)
display(antispiegel_top_tokens_df)
# Same BERTopic configuration as RT_de
antispiegel_topic_model = BERTopic(
    language='multilingual',
    embedding_model='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
    min_topic_size=25,
    calculate_probabilities=False,
    verbose=True,
)
antispiegel_topics, _ = antispiegel_topic_model.fit_transform(antispiegel_docs)
antispiegel_topic_info = antispiegel_topic_model.get_topic_info()
display(antispiegel_topic_info.head(20))
display(antispiegel_topic_model.visualize_barchart(top_n_topics=12))

Antispiegel articles used: 914
Antispiegel chunks used for BERTopic: 5493
Date range: 2025-04-10 to 2026-02-10

          token  count
0      russland  10035
1       ukraine   7533
2     antworten   6723
3      anmelden   6382
4            eu   6131
5        teilen   5612
6           usa   5424
7         trump   5041
8       spiegel   3900
9           mai   3856
10  deutschland   3769
11           us   3590
12       medien   3161
13        krieg   3095
14   russischen   2927
15       europa   2699
16         anti   2651
17        april   2497
18        putin   2432
19    regierung   2407

2026-02-19 19:59:06,074 - BERTopic - Embedding - Transforming documents to embeddings.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/172 [00:00<?, ?it/s]

2026-02-19 19:59:45,504 - BERTopic - Embedding - Completed ✓
2026-02-19 19:59:45,507 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-19 19:59:47,202 - BERTopic - Dimensionality - Completed ✓
2026-02-19 19:59:47,203 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-19 19:59:47,336 - BERTopic - Cluster - Completed ✓
2026-02-19 19:59:47,338 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-19 19:59:47,845 - BERTopic - Representation - Completed ✓

   Topic  Count                                   Name  \
0     -1    328         -1_russland_usa_spiegel_teilen
1      0   4665  0_russland_ukraine_antworten_anmelden
2      1    204        1_israel_gaza_israelische_hamas
3      2    145      2_moldawien_wahlen_sandu_rumänien
4      3     46               3_venezuela_usa_trump_us
5      4     39    4_april_anmelden_antworten_menschen
6      5     35         5_grönland_dänemark_usa_arktis
7      6     31      6_tacheles_teilen_sendung_freitag

                                                                                        Representation  \
0                           [russland, usa, spiegel, teilen, trump, anti, us, eu, antworten, anmelden]
1                   [russland, ukraine, antworten, anmelden, eu, teilen, usa, trump, mai, deutschland]
2     [israel, gaza, israelische, hamas, netanjahu, israelischen, israels, gazastreifen, teilen, iran]
3  [moldawien, wahlen, sandu, rumänien, wahl, regierung, eu, parlamentswahlen, moldawischen, russland]
4      [venezuela, usa, trump, us, maduro, öl, venezuelas, venezolanischen, venezolanische, regierung]
5                 [april, anmelden, antworten, menschen, wasser, artikel, mal, fische, hormone, pille]
6                      [grönland, dänemark, usa, arktis, grönlands, trump, kanada, us, nato, dänische]
7                   [tacheles, teilen, sendung, freitag, stein, anti, lebt, osteuropa, beitrag, röper]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Representative_Docs
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [bedeuten trumps ambitionen grönland nato folge anti spiegel podcasts trumps angriff venezuela ansprüche grönland frage all völkerrecht europäer nato bedeutet anti spiegel podcast bedeuten trumps ambitionen grönland nato folge anti spiegel podcasts trumps angriff venezuela ansprüche grönland frage all völkerrecht europäer nato bedeutet anti spiegel januar jahres geopolitische veränderungen gebracht folge anti spiegel podcasts trumps angriff venezuela ansprüche grönland folgen bedeutet europa nato völkerrecht insgesamt anti spiegel podcast spotify russischen vk anhören teile beitrag teilen teilen teilen teilen teilen mail teilen autor anti spiegel thomas röper geboren experte osteuropa finanzdienstleistungsunternehmen osteuropa russland vorstands aufsichtsratspositionen bekleidet lebt wahlheimat st petersburg lebt russland spricht fließend russisch schwerpunkte medienkritischen arbeit mediale russlandbild deutschland kritik berichterstattung westlicher medien themen geo politik wirtschaft nächster beitrag medienberichte letzten verschiedene pläne usa grönland übernehmen, ukraine verhandlungen epstein gasspeicher fragen antworten mal anti spiegel podcast sammlung vieler themen derzeit fragen antworten interessant anti spiegel podcast ukraine verhandlungen epstein gasspeicher fragen antworten mal anti spiegel podcast sammlung vieler themen derzeit fragen antworten interessant anti spiegel februar derzeit themen fragen antworten stand ukraine verhandlungen genau steht millionen seiten epstein akten reicht gas deutschland themen mal anti spiegel podcast besprochen wenigen vorhandenen informationen ausgesprochen vielsagend anti spiegel podcast spotify russischen vk anhören teile beitrag teilen teilen teilen teilen teilen mail teilen autor anti spiegel thomas röper geboren experte osteuropa finanzdienstleistungsunternehmen osteuropa russland vorstands aufsichtsratspositionen bekleidet lebt wahlheimat st petersburg lebt russland spricht fließend russisch schwerpunkte medienkritischen arbeit mediale russlandbild deutschland kritik berichterstattung westlicher medien themen geo politik wirtschaft nächster beitrag friedensverhandlungen verzweiflung ukraine, stahlkrise deutschland reiseboom russland politischen anti spiegel podcasts wirtschaftliche themen reiseboom russland gesprochen anti spiegel podcast stahlkrise deutschland reiseboom russland politischen anti spiegel podcasts wirtschaftliche themen reiseboom russland gesprochen anti spiegel november besteht anti spiegel podcast teilen politische themen krise stahlindustrie deutschland gründe gesprochen leben russland gewidmet mal thema reisen russland frage gesprochen wohin russen reisen europa willkommen anti spiegel podcast spotify russischen vk anhören teile beitrag teilen teilen teilen teilen teilen mail teilen autor anti spiegel thomas röper geboren experte osteuropa finanzdienstleistungsunternehmen osteuropa russland vorstands aufsichtsratspositionen bekleidet lebt wahlheimat st petersburg lebt russland spricht fließend russisch schwerpunkte medienkritischen arbeit mediale russlandbild deutschland kritik berichterstattung westlicher medien themen geo politik wirtschaft nächster beitrag spekulationen russlands waffensysteme]

18it [00:05,  3.16it/s]

,Topic,Words,Frequency,Timestamp
0,-1,"april, russland, antworten, anmelden, usa",30,2025-04-09 16:39:21.600
1,0,"april, antworten, anmelden, russland, ukraine",624,2025-04-09 16:39:21.600
2,1,"israel, türkei, teilen, iran, atomwaffen",2,2025-04-09 16:39:21.600
3,2,"moldawien, sandu, gagausien, kirche, regierung",10,2025-04-09 16:39:21.600
4,4,"april, anmelden, antworten, menschen, mal",26,2025-04-09 16:39:21.600
5,6,"tacheles, stein, teilen, sendung, robert",1,2025-04-09 16:39:21.600
6,-1,"pakistan, indien, antworten, anmelden, trump",28,2025-04-25 07:12:00.000
7,0,"antworten, anmelden, mai, russland, ukraine",477,2025-04-25 07:12:00.000
8,1,"israel, gaza, the, mai, of",11,2025-04-25 07:12:00.000
9,2,"moldawien, wahlen, sandu, rumänien, maia",19,2025-04-25 07:12:00.000
10,6,"tacheles, freitag, teilen, sendung, maifeiertages",1,2025-04-25 07:12:00.000
11,-1,"mai, antworten, anmelden, burkina, faso",24,2025-05-10 14:24:00.000
12,0,"mai, antworten, anmelden, russland, ukraine",493,2025-05-10 14:24:00.000
13,1,"israel, hamas, mai, gaza, gazastreifen",28,2025-05-10 14:24:00.000
14,2,"rumänien, simion, moldawien, wahl, rumäniens",16,2025-05-10 14:24:00.000
15,6,"tacheles, teilen, sendung, freitag, rennt",1,2025-05-10 14:24:00.000
16,-1,"antworten, anmelden, russland, trump, afrika",37,2025-05-25 21:36:00.000
17,0,"antworten, anmelden, juni, russland, ukraine",611,2025-05-25 21:36:00.000
18,1,"israel, gaza, israelische, iran, mai",23,2025-05-25 21:36:00.000
19,2,"moldawien, rumänien, wahlen, wahl, eu",13,2025-05-25 21:36:00.000

### Antispiegel — Dynamic Topic Modelling (over time)

In [ ]:
# Topics over time (same as RT_de)
antispiegel_topics_over_time = antispiegel_topic_model.topics_over_time(
    docs=antispiegel_docs,
    timestamps=antispiegel_timestamps,
    nr_bins=20,
)

display(antispiegel_topics_over_time.head(20))

display(antispiegel_topic_model.visualize_topics_over_time(
    antispiegel_topics_over_time,
    top_n_topics=10,
))

## Apollo — Topic Modelling (same pipeline as RT_de)

In [127]:
# Apollo topic modelling (same pipeline as RT_de)
# Uses the same cleaning, chunking, BERTopic setup, and outputs as RT_de.
if 'BERTopic' not in globals() or 'clean_topic_text' not in globals() or 'chunk_text' not in globals():
    raise RuntimeError('Please run the RT_de topic modelling cell first.')
apollo_source_key = next((k for k in dfs_by_source if k.lower() == 'apollo'), None)
if apollo_source_key is None:
    raise KeyError(f"Source not found for Apollo. Available sources: {list(dfs_by_source.keys())}")
apollo_topic_df = dfs_by_source[apollo_source_key].copy()
required_cols = {'Inhalt', 'Date'}
missing_cols = required_cols.difference(apollo_topic_df.columns)
if missing_cols:
    raise KeyError(f"Missing required columns for Apollo: {sorted(missing_cols)}")
# Keep only rows with available full text
apollo_topic_df = apollo_topic_df[apollo_topic_df['Inhalt'].notna()].copy()
# Same topic columns as RT_de
apollo_topic_df['topic_text_raw'] = apollo_topic_df['Inhalt'].astype(str)
apollo_topic_df['topic_date'] = pd.to_datetime(apollo_topic_df['Date'], errors='coerce')
# Same cleaning pipeline as RT_de
apollo_topic_df['topic_text_clean'] = apollo_topic_df['topic_text_raw'].apply(clean_topic_text)
apollo_topic_df['topic_text_model'] = apollo_topic_df['topic_text_clean']
# Same chunking pipeline as RT_de
apollo_topic_df['topic_chunks'] = apollo_topic_df['topic_text_model'].apply(chunk_text)
apollo_model_df = (
    apollo_topic_df[['topic_date', 'topic_chunks']]
    .explode('topic_chunks')
    .rename(columns={'topic_chunks': 'topic_text_model'})
)
apollo_model_df = apollo_model_df[
    apollo_model_df['topic_date'].notna()
    & apollo_model_df['topic_text_model'].notna()
    & apollo_model_df['topic_text_model'].str.len().gt(0)
].copy()
# Full corpus by default (no sampling)
MAX_DOCS = None
if MAX_DOCS is not None and len(apollo_model_df) > MAX_DOCS:
    apollo_model_df = apollo_model_df.sample(MAX_DOCS, random_state=42)
apollo_model_df = apollo_model_df.sort_values('topic_date').reset_index(drop=True)
if apollo_model_df.empty:
    raise ValueError('No usable chunks after preprocessing.')
apollo_docs = apollo_model_df['topic_text_model'].tolist()
apollo_timestamps = apollo_model_df['topic_date'].dt.to_pydatetime().tolist()
print(f'Apollo articles used: {apollo_topic_df["topic_date"].notna().sum()}')
print(f'Apollo chunks used for BERTopic: {len(apollo_docs)}')
print(f'Date range: {apollo_model_df["topic_date"].min().date()} to {apollo_model_df["topic_date"].max().date()}')
# Same sanity check as RT_de
apollo_token_counts = Counter(' '.join(apollo_topic_df['topic_text_clean']).split())
apollo_top_tokens_df = pd.DataFrame(apollo_token_counts.most_common(20), columns=['token', 'count'])
# Overall non-time topic overview (all documents/chunks)
display(apollo_top_tokens_df)
# Same BERTopic configuration as RT_de
apollo_topic_model = BERTopic(
    language='multilingual',
    embedding_model='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
    min_topic_size=25,
    calculate_probabilities=False,
    verbose=True,
)
apollo_topics, _ = apollo_topic_model.fit_transform(apollo_docs)
apollo_topic_info = apollo_topic_model.get_topic_info()
display(apollo_topic_info.head(20))
display(apollo_topic_model.visualize_barchart(top_n_topics=12))

Apollo articles used: 3550
Apollo chunks used for BERTopic: 5283
Date range: 2025-08-12 to 2026-02-10

               token  count
0                pay   7077
1            werbung   6967
2               news   4989
3             apollo   4899
4            prozent   4468
5             zahlen   4029
6             teilen   3739
7       unterstützen   3715
8               bank   3639
9          monatlich   3569
10               afd   3551
11          einmalig   3547
12       überweisung   3541
13       kommentaren   3540
14  zahlungsoptionen   3537
15       deutschland   2709
16              euro   2407
17         redaktion   2056
18             lesen   2043
19               spd   2034

2026-02-19 19:59:54,955 - BERTopic - Embedding - Transforming documents to embeddings.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/166 [00:00<?, ?it/s]

2026-02-19 20:00:37,818 - BERTopic - Embedding - Completed ✓
2026-02-19 20:00:37,819 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-19 20:00:39,475 - BERTopic - Dimensionality - Completed ✓
2026-02-19 20:00:39,477 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-19 20:00:39,596 - BERTopic - Cluster - Completed ✓
2026-02-19 20:00:39,599 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-19 20:00:40,049 - BERTopic - Representation - Completed ✓

,Topic,Count,Name,Representation,Representative_Docs
0,0,5067,0_werbung_pay_news_apollo,"[werbung, pay, news, apollo, prozent, afd, zahlen, teilen, unterstützen, kommentaren]","[monate wahl berliner abgeordnetenhaus verliert cdu regierenden bürgermeisters kai wegner spürbar rückhalt zeigt mittwoch veröffentlichte erhebung instituts infratest dimap sender rbb aktuellen zahlen schwarz rote koalition cdu spd mehrheit deutlich eingebüßt ergebnis sinkende werte beider regierungsparteien zurückgeht berlintrend sieht cdu derzeit prozent punkte juni punkte abgeordnetenhauswahl februar werbung unverändert platz liegt linkspartei prozent afd gewinnt hinzu erreicht prozent grünen punkt ebenfalls prozent steigen spd fällt prozent bündnis sahra wagenknecht verpasst prozent prozent hürde kleinere parteien prozent ergebnissen ergeben mehrere theoretische mehrheitskonstellationen weiterhin cdu geführte regierung einbindung grünen spd alternativ käme rot grün rotes bündnis führung linkspartei betracht werbung zusammenarbeit afd schließen parteien weiterhin cdu lehnt zudem bündnis linkspartei nächste wahl berliner abgeordnetenhaus findet september ha teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, afd erreicht mecklenburg vorpommern höchstwert laut umfrage infratest dimap auftrag ndr liegt partei prozent april insa erhebung nordkurier afd prozent gesehen zuwachs fast punkten wenigen monaten spd fällt aktuellen erhebung prozent landtagswahl prozent erzielt ergebnis halbieren schwäche profitiert afd cdu hingegen bleibt trotz oppositionsrolle prozent historischen tiefstand linke verbessert prozent bündnis sahra wagenknecht sinkt prozent grünen liegen prozent knapp sperrklausel werbung prozent befragten arbeit rot roten koalition unzufrieden prozent zufrieden ministerpräsidentin manuela schwesig schneidet vergleich prozent zufrieden prozent fortsetzung rot roten koalition rechnerisch bündnis spd cdu linken mehrheit erreichen regierung afd viererbündnis notwendig spd cdu linken grünen spd cdu linken bsw fällen müsste cdu linken kooperieren werbung mecklenburg vorpommern reiht serie ostdeutscher afd bestwerte sachsen anhalt gewählt lag partei zuletzt prozent thüringen prozent bundestagswahl februar afd nordosten klar stärkste kraft mecklenburg vorpommern erreichte prozent zweitstimmen gewann direktmandate cm teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, aktuellen erhebung meinungsforschungsinstituts insa bild sonntag bleibt afd prozent unverändert stärkste politische kraft deutschland union sonntagstrend prozentpunkt hinzugewinnen erreicht prozent spd verharrt prozent werte grünen linken bleiben stabil jeweils prozent fdp verliert punkt prozent bsw prozent unverändert bleibt sonstige parteien entfallen prozent stimmen delivered by ama setzt leichte aufwärtstrend union fort rangfolge parteien ändert afd liegt weiterhin knapp cdu csu parteipräferenzen fragte insa haltung sogenannten brandmauer afd klare mehrheit unionsanhänger steht kurs parteiführung positiv prozent wähler cdu csu begrüßen zusammenarbeit afd ausgeschlossen prozent unionsanhänger halten brandmauer falsch werbung gesamtbevölkerung finden laut insa umfrage bild sonntag prozent befragten brandmauer prozent ablehnen reihen union brandmauerkritische stimmen lauter gleichwohl betont merz afd hauptgegner kommenden wahlen partei wolle cdu erklärtermaßen zerstören warnte parteivorsitzende ha teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung]"
1,1,61,1_pay_überweisung_zahlungsoptionen_bank,"[pay, überweisung, zahlungsoptionen, bank, einmalig, monatlich, unterstützen, teilen, kommentaren, zahlen]","[teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung]"
2,2,55,2_pay_überweisung_zahlungsoptionen_bank,"[pay, überweisung, zahlungsoptionen, bank, einmalig, monatlich, unterstützen, teilen, kommentaren, zahlen]","[teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung]"
3,3,35,3_pay_überweisung_zahlungsoptionen_bank,"[pay, überweisung, zahlungsoptionen, bank, einmalig, kommentaren, monatlich, unterstützen, teilen, zahlen]","[teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung]"
4,4,34,4_pay_überweisung_zahlungsoptionen_bank,"[pay, überweisung, zahlungsoptionen, bank, einmalig, kommentaren, monatlich, unterstützen, teilen, zahlen]","[teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung]"
5,5,31,5_pay_überweisung_zahlungsoptionen_bank,"[pay, überweisung, zahlungsoptionen, bank, einmalig, monatlich, unterstützen, teilen, zahlen, kommentaren]","[teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung, teilen kommentaren einmalig monatlich apollo news unterstützen zahlungsoptionen pay pay zahlen bank überweisung]"

20it [00:06,  3.20it/s]

,Topic,Words,Frequency,Timestamp
0,0,"afd, pay, apollo, news, prozent",16,2025-08-11 19:37:55.200
1,0,"werbung, pay, prozent, news, apollo",219,2025-08-21 02:24:00.000
2,1,"pay, überweisung, zahlungsoptionen, bank, einmalig",3,2025-08-21 02:24:00.000
3,2,"pay, überweisung, zahlungsoptionen, bank, einmalig",3,2025-08-21 02:24:00.000
4,4,"pay, überweisung, zahlungsoptionen, bank, einmalig",3,2025-08-21 02:24:00.000
5,5,"pay, überweisung, zahlungsoptionen, bank, einmalig",3,2025-08-21 02:24:00.000
6,0,"pay, werbung, prozent, apollo, news",212,2025-08-30 04:48:00.000
7,1,"pay, überweisung, zahlungsoptionen, bank, einmalig",1,2025-08-30 04:48:00.000
8,2,"pay, überweisung, zahlungsoptionen, bank, einmalig",5,2025-08-30 04:48:00.000
9,4,"pay, überweisung, zahlungsoptionen, bank, einmalig",4,2025-08-30 04:48:00.000
10,5,"pay, überweisung, zahlungsoptionen, bank, einmalig",2,2025-08-30 04:48:00.000
11,0,"kirk, pay, werbung, prozent, news",242,2025-09-08 07:12:00.000
12,1,"pay, überweisung, zahlungsoptionen, bank, einmalig",4,2025-09-08 07:12:00.000
13,2,"pay, überweisung, zahlungsoptionen, bank, einmalig",2,2025-09-08 07:12:00.000
14,3,"pay, überweisung, zahlungsoptionen, bank, einmalig",6,2025-09-08 07:12:00.000
15,4,"pay, überweisung, zahlungsoptionen, bank, einmalig",1,2025-09-08 07:12:00.000
16,5,"pay, überweisung, zahlungsoptionen, bank, einmalig",1,2025-09-08 07:12:00.000
17,0,"werbung, pay, prozent, news, apollo",237,2025-09-17 09:36:00.000
18,1,"pay, überweisung, zahlungsoptionen, bank, einmalig",6,2025-09-17 09:36:00.000
19,2,"pay, überweisung, zahlungsoptionen, bank, einmalig",2,2025-09-17 09:36:00.000

### Apollo — Dynamic Topic Modelling (over time)

In [ ]:
# Topics over time (same as RT_de)
apollo_topics_over_time = apollo_topic_model.topics_over_time(
    docs=apollo_docs,
    timestamps=apollo_timestamps,
    nr_bins=20,
)

display(apollo_topics_over_time.head(20))

display(apollo_topic_model.visualize_topics_over_time(
    apollo_topics_over_time,
    top_n_topics=10,
))

## Compact — Topic Modelling (same pipeline as RT_de)

In [128]:
# Compact topic modelling (same pipeline as RT_de)
# Uses the same cleaning, chunking, BERTopic setup, and outputs as RT_de.
if 'BERTopic' not in globals() or 'clean_topic_text' not in globals() or 'chunk_text' not in globals():
    raise RuntimeError('Please run the RT_de topic modelling cell first.')
compact_source_key = next((k for k in dfs_by_source if k.lower() == 'compact'), None)
if compact_source_key is None:
    raise KeyError(f"Source not found for Compact. Available sources: {list(dfs_by_source.keys())}")
compact_topic_df = dfs_by_source[compact_source_key].copy()
required_cols = {'Inhalt', 'Date'}
missing_cols = required_cols.difference(compact_topic_df.columns)
if missing_cols:
    raise KeyError(f"Missing required columns for Compact: {sorted(missing_cols)}")
# Keep only rows with available full text
compact_topic_df = compact_topic_df[compact_topic_df['Inhalt'].notna()].copy()
# Same topic columns as RT_de
compact_topic_df['topic_text_raw'] = compact_topic_df['Inhalt'].astype(str)
compact_topic_df['topic_date'] = pd.to_datetime(compact_topic_df['Date'], errors='coerce')
# Same cleaning pipeline as RT_de
compact_topic_df['topic_text_clean'] = compact_topic_df['topic_text_raw'].apply(clean_topic_text)
compact_topic_df['topic_text_model'] = compact_topic_df['topic_text_clean']
# Same chunking pipeline as RT_de
compact_topic_df['topic_chunks'] = compact_topic_df['topic_text_model'].apply(chunk_text)
compact_model_df = (
    compact_topic_df[['topic_date', 'topic_chunks']]
    .explode('topic_chunks')
    .rename(columns={'topic_chunks': 'topic_text_model'})
)
compact_model_df = compact_model_df[
    compact_model_df['topic_date'].notna()
    & compact_model_df['topic_text_model'].notna()
    & compact_model_df['topic_text_model'].str.len().gt(0)
].copy()
# Full corpus by default (no sampling)
MAX_DOCS = None
if MAX_DOCS is not None and len(compact_model_df) > MAX_DOCS:
    compact_model_df = compact_model_df.sample(MAX_DOCS, random_state=42)
compact_model_df = compact_model_df.sort_values('topic_date').reset_index(drop=True)
if compact_model_df.empty:
    raise ValueError('No usable chunks after preprocessing.')
compact_docs = compact_model_df['topic_text_model'].tolist()
compact_timestamps = compact_model_df['topic_date'].dt.to_pydatetime().tolist()
print(f'Compact articles used: {compact_topic_df["topic_date"].notna().sum()}')
print(f'Compact chunks used for BERTopic: {len(compact_docs)}')
print(f'Date range: {compact_model_df["topic_date"].min().date()} to {compact_model_df["topic_date"].max().date()}')
# Same sanity check as RT_de
compact_token_counts = Counter(' '.join(compact_topic_df['topic_text_clean']).split())
compact_top_tokens_df = pd.DataFrame(compact_token_counts.most_common(20), columns=['token', 'count'])
# Overall non-time topic overview (all documents/chunks)
display(compact_top_tokens_df)
# Same BERTopic configuration as RT_de
compact_topic_model = BERTopic(
    language='multilingual',
    embedding_model='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
    min_topic_size=25,
    calculate_probabilities=False,
    verbose=True,
)
compact_topics, _ = compact_topic_model.fit_transform(compact_docs)
compact_topic_info = compact_topic_model.get_topic_info()
display(compact_topic_info.head(20))
display(compact_topic_model.visualize_barchart(top_n_topics=12))

Compact articles used: 2045
Compact chunks used for BERTopic: 3768
Date range: 2025-06-11 to 2026-02-10

          token  count
0       compact   3399
1           afd   2088
2   deutschland   1358
3            us   1261
4      erfahren   1248
5     bestellen   1205
6         trump   1166
7       prozent   1131
8           q10   1013
9          foto    999
10    deutschen    990
11     menschen    964
12          usa    909
13         euro    905
14        sogar    862
15     russland    859
16   geschichte    729
17        krieg    728
18     deutsche    719
19      ausgabe    714

2026-02-19 20:00:47,306 - BERTopic - Embedding - Transforming documents to embeddings.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/118 [00:00<?, ?it/s]

2026-02-19 20:01:16,032 - BERTopic - Embedding - Completed ✓
2026-02-19 20:01:16,033 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-19 20:01:23,822 - BERTopic - Dimensionality - Completed ✓
2026-02-19 20:01:23,823 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-19 20:01:23,899 - BERTopic - Cluster - Completed ✓
2026-02-19 20:01:23,901 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-19 20:01:24,249 - BERTopic - Representation - Completed ✓

    Topic  Count                                     Name  \
0      -1   1122            -1_afd_compact_deutschland_us
1       0    533       0_geschichte_deutschen_compact_afd
2       1    418    1_q10_entzündungen_stress_astaxanthin
3       2    280   2_passwort_printausgabe_desktop_loggen
4       3    273           3_russland_ukraine_putin_krieg
5       4    166  4_israel_netanjahu_israelischen_israels
6       5    117       5_compact_tv_unterstuetzen_spenden
7       6    108              6_asyl_euro_deutschland_afd
8       7     90     7_silber_gold_dollar_silbermedaillen
9       8     90          8_antifa_hammerbande_maja_szene
10      9     88             9_messer_morde_opfer_polizei
11     10     81                    10_afd_cdu_spd_partei
12     11     78               11_venezuela_maduro_us_usa
13     12     47         12_corona_witzschel_impfung_piks
14     13     45              13_euro_brd_diktatur_seiten
15     14     40          14_polizei_täter_messer_mädchen
16     15     38          15_compact_bestellen_afd_verbot
17     16     37                16_prozent_afd_bsw_partei
18     17     34         17_epstein_trump_epsteins_greene
19     18     29                18_mars_ufo_planeten_musk

                                                                                                       Representation  \
0                                     [afd, compact, deutschland, us, trump, bestellen, foto, erfahren, prozent, usa]
1                       [geschichte, deutschen, compact, afd, foto, deutsche, deutschland, erfahren, bestellen, buch]
2                [q10, entzündungen, stress, astaxanthin, vitamin, körper, zellen, immunsystem, magnesium, ernährung]
3   [passwort, printausgabe, desktop, loggen, benutzern, zurückzusetzen, benutzername, klicke, tablet, registrierten]
4                                  [russland, ukraine, putin, krieg, trump, nato, russischen, frieden, russische, eu]
5                               [israel, netanjahu, israelischen, israels, gaza, iran, trump, israelische, hamas, us]
6                               [compact, tv, unterstuetzen, spenden, gratis, unterstützung, bitte, klemm, paul, afd]
7                         [asyl, euro, deutschland, afd, migranten, invasion, paket, merkel, asylbewerber, bestellen]
8                               [silber, gold, dollar, silbermedaillen, euro, prozent, compact, preis, us, medaillen]
9               [antifa, hammerbande, maja, szene, linksextremisten, linksextreme, compact, anhänger, dresden, linke]
10                                 [messer, morde, opfer, polizei, mädchen, täter, gewalt, spezial, compact, jährige]
11                                              [afd, cdu, spd, partei, prozent, weidel, alice, merz, union, stimmen]
12                         [venezuela, maduro, us, usa, präsident, venezuelas, washington, trump, caracas, rodriguez]
13                             [corona, witzschel, impfung, piks, dr, aufarbeitung, bianca, dvd, maßnahmen, pandemie]
14                                          [euro, brd, diktatur, seiten, afd, spd, paket, demokratie, merz, brosius]
15                           [polizei, täter, messer, mädchen, jährige, opfer, angreifer, konarek, mann, eigenschutz]
16                       [compact, bestellen, afd, verbot, demokratie, brosius, meinungsfreiheit, corona, brd, spahn]
17                                     [prozent, afd, bsw, partei, wähler, wagenknecht, politik, sachsen, kickl, fpö]
18                                    [epstein, trump, epsteins, greene, akten, jeffrey, maxwell, us, trumps, mossad]
19                            [mars, ufo, planeten, musk, außerirdischen, spacex, erde, däniken, antarktis, starship]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Representative_Docs
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           [februar forderte afd genau donald trump umsetzt führung petr bystron legte bundestag umfangreichen friedensplan plan ernst genommen wären deutschland europa fast krieg blutvergießen milliardenkosten erspart geblieben zeigt klar afd lag anfang dürfte gründe weshalb partei stärkeren zuspruch erfährt politikwissenschaftler werner patzelt analysiert erfolg afd exzellent bemerkenswertes buch blaue wunder aufstieg afd compact shop erhältlich erfahren team petr bystron nato erweiterung afd plan februar setzte sofortige verhandlungen internationale vermittlung neutrale ukraine nato beitritt forderte klare sicherheitsordnung ausländische truppen raketen atomwaffen osze überwachte feuerpause stufenplan rückzug russischer truppen reduzierung westlicher waffenlieferungen verbindet genau linie taucht trump friedensplan trump verlangt neutralität direkte gespräche sicherheitsgarantien seiten nato erweiterung zeigt washington moskau herrscht einigkeit ursachen krieges petr bystron afd europaparlament foto compact trump zugeständnisse moskau afd trump plan punkten hinaus afd forderte verankert parlamentswahlen ukraine binnen hundert fixiert territorialen linien beider staaten politische realität schafft wirtschaftliche großprojekte usa russland form afd plan standen sieht rückkehr russlands weltwirtschaft wiedereinladung g8 weitreichend territorialen zugeständnisse trump erkennt russische kontrolle krim teile donbass faktisch legt kontaktlinien dauerhafte grenzrealität fest bystrons initiative deutlich ausgewogener setzte internationale referenden rückkehr geflüchteten verhandelte lösung kreml territoriale gewinne endgültig zuzusprechen afd plan blutvergießen verhindert afd forderte sofortigen waffenstillstand bundesregierung lehnte kurs obwohl ausstieg abnutzungskrieg pläne tisch lagen starben ukrainekrieg anfang mehrere hunderttausend menschen schätzungen deutlich dreihunderttausend gefallenen soldaten beider seiten zahlreiche zivile opfer bundesregierung, afd erreicht umfrage rekord setzt nunmehr klar union aktuellen buch deutschlands blaues wunder analysiert politikwissenschaftler werner patzelt situation deutschland erklärt afd profitieren regieren erfahren afd setzt aufwärtstrend bundesweiten umfragen fort markiert höchststand aktuellen erhebung gesellschaft markt sozialforschung gms blauen prozent liegen erstmals klaren abstand cdu csu prozent hoffen derart deutlicher vorsprung union zuvor bundesweiten umfrage gemessen scholz merz zahlen unterstreichen tiefgreifenden wandel wählerlandschaft dokumentieren anhaltende verschiebung zugunsten afd menschen offenbar endgültig kriegsparteien scholz merz spricht lande herum bezeichnend blick entwicklung innerhalb jahres gms umfrage anfang januar union deutlich geführt cdu csu lagen prozent afd prozent erreichte gewann afd prozentpunkte hinzu union gleichen zeitraum punkte verlor insgesamt bedeutet verschiebung prozentpunkten zugunsten afd außergewöhnlicher vorgang kurzer platz insa übrigen parteien zeigt geringe veränderung spd prozent grünen erreichen prozent linke verliert steht prozent bündnis sahra wagenknecht bleibt prozent prozent marke fdp erreicht prozent freien wähler prozent sonstige parteien prozent ähnliches bild zeichnet aktuelle umfrage instituts insa liegt afd prozent ebenfalls spitze knapp union prozent aktuellen zahlen bestätigen eindrucksvollen aufwärtstrend afd spd cdu csu redlich verdient aktuellen buch deutschlands blaues wunder analysiert politikwissenschaftler werner patzelt situation deutschland erklärt afd profitieren regieren bestellen, parteichef tino chrupalla erstmals compact interview afd außenpolitikexperte markus frohnmaier spitzenkandidat blauen landtagswahl baden württemberg ulrich siegmund spitzenkandidat afd landtagswahl sachsen anhalt unserem dossier america first welt beleuchten zudem national security strategy us präsident trump geopolitischen kurs festgelegt hebt scharf vorgängern erwähnt völkerrecht wort nennt europäischen rechtsparteien afd partner regierung washington dokumentieren trump doktrin deutscher übersetzung europa kapitel sogar vollständig fakten heft einzelnen finden folgende beiträge titelthema usa afd gefährliche liebschaft februar ausgabe gefährliche liebschaft usa afd paardiagnose usa afd traumpaar donald trumps außenpolitische aggressionen jahresanfang zwingen größte deutsche oppositionspartei entscheidung weg folgen antworten fallen krass unterschiedlich nato tino chrupalla interview afd co vorsitzende warnt wildwest situation globus donald trump stärkeren gilt streitpunkt grönland überraschenden vorschlag bisschen baerbock markus frohnmaier gespräch afd spitzenkandidat baden württemberg sieht us intervention venezuela völkerrechtsbruch trumps absage regelbasierte ordnung biete chancen deutschland nutzen müsse russland setzt akzente imperium freund uncle sam samthandschuhe afd selektive wahrnehmung völkerrechts aufgibt usa schont unterscheidet kartellparteien kritisiert februar ausgabe titelthema usa afd gefährliche liebschaft kiosk erhältlich ausgabe bequem bestellen beginnen ausgabe abo komplette inhaltsverzeichnis compact titelthema gefährliche liebschaft usa afd paardiagnose nato tino chrupalla interview bisschen baerbock markus frohnmaier gespräch imperium freund uncle sam samthandschuhe politik schnell liefern ulrich siegmund gespräch strom stadt tod winter terror berlin blackout verschwörung spuren tiefen staat drogenschwindel kriegslügen venezuela fluch schwarzen pampe öl maduro]

20it [00:04,  4.47it/s]

,Topic,Words,Frequency,Timestamp
0,-1,"soros, compact, us, welt, prozent",67,2025-06-10 18:08:38.400
1,0,"inka, geschichte, dionysos, normannen, foto",32,2025-06-10 18:08:38.400
2,1,"q10, astaxanthin, stress, entzündungen, zucker",16,2025-06-10 18:08:38.400
3,2,"passwort, printausgabe, klicke, desktop, benutzername",10,2025-06-10 18:08:38.400
4,3,"russland, frieden, spd, putin, trump",11,2025-06-10 18:08:38.400
5,4,"israel, iran, israelischen, netanjahu, israels",42,2025-06-10 18:08:38.400
6,5,"compact, unterstuetzen, spenden, tv, gratis",4,2025-06-10 18:08:38.400
7,6,"euro, asyl, kirchenasyl, abschiebungen, asylbewerber",8,2025-06-10 18:08:38.400
8,7,"blockchain, technologie, löbe, finanzämtern, zuschauergalerie",1,2025-06-10 18:08:38.400
9,8,"maja, antifa, hammerbande, ungarn, behörden",7,2025-06-10 18:08:38.400
10,9,"opfer, messer, hammer, messias, somalier",4,2025-06-10 18:08:38.400
11,10,"spd, frey, afd, cdu, spahn",4,2025-06-10 18:08:38.400
12,12,"corona, witzschel, dr, euro, aufarbeitung",6,2025-06-10 18:08:38.400
13,13,"euro, bundeskanzler, bargeld, art, drecksarbeit",4,2025-06-10 18:08:38.400
14,14,"gruppe, tiger, white, hamburger, täter",1,2025-06-10 18:08:38.400
15,15,"frey, euro, grundrechte, spahn, dehler",3,2025-06-10 18:08:38.400
16,16,"wähler, freien, landtagswahl, partei, afd",2,2025-06-10 18:08:38.400
17,18,"ufo, antarktis, mars, signale, außerirdische",9,2025-06-10 18:08:38.400
18,-1,"compact, trump, massie, afd, musk",48,2025-06-23 04:48:00.000
19,0,"compact, rapanui, kocak, fund, zeigen",13,2025-06-23 04:48:00.000

### Compact — Dynamic Topic Modelling (over time)

In [ ]:
# Topics over time (same as RT_de)
compact_topics_over_time = compact_topic_model.topics_over_time(
    docs=compact_docs,
    timestamps=compact_timestamps,
    nr_bins=20,
)

display(compact_topics_over_time.head(20))

display(compact_topic_model.visualize_topics_over_time(
    compact_topics_over_time,
    top_n_topics=10,
))

## deusch_pravda — Topic Modelling (same pipeline as RT_de)

In [129]:
# deusch_pravda topic modelling (same pipeline as RT_de)
# Uses the same cleaning, chunking, BERTopic setup, and outputs as RT_de.
if 'BERTopic' not in globals() or 'clean_topic_text' not in globals() or 'chunk_text' not in globals():
    raise RuntimeError('Please run the RT_de topic modelling cell first.')
deusch_pravda_source_key = next((k for k in dfs_by_source if k.lower() == 'deusch_pravda'), None)
if deusch_pravda_source_key is None:
    raise KeyError(f"Source not found for deusch_pravda. Available sources: {list(dfs_by_source.keys())}")
deusch_pravda_topic_df = dfs_by_source[deusch_pravda_source_key].copy()
required_cols = {'full_text', 'time'}
missing_cols = required_cols.difference(deusch_pravda_topic_df.columns)
if missing_cols:
    raise KeyError(f"Missing required columns for deusch_pravda: {sorted(missing_cols)}")
# Keep only rows with available full text
deusch_pravda_topic_df = deusch_pravda_topic_df[deusch_pravda_topic_df['full_text'].notna()].copy()
# Same topic columns as RT_de
deusch_pravda_topic_df['topic_text_raw'] = deusch_pravda_topic_df['full_text'].astype(str)
deusch_pravda_topic_df['topic_date'] = pd.to_datetime(deusch_pravda_topic_df['time'], errors='coerce')
# Same cleaning pipeline as RT_de
deusch_pravda_topic_df['topic_text_clean'] = deusch_pravda_topic_df['topic_text_raw'].apply(clean_topic_text)
deusch_pravda_topic_df['topic_text_model'] = deusch_pravda_topic_df['topic_text_clean']
# Same chunking pipeline as RT_de
deusch_pravda_topic_df['topic_chunks'] = deusch_pravda_topic_df['topic_text_model'].apply(chunk_text)
deusch_pravda_model_df = (
    deusch_pravda_topic_df[['topic_date', 'topic_chunks']]
    .explode('topic_chunks')
    .rename(columns={'topic_chunks': 'topic_text_model'})
)
deusch_pravda_model_df = deusch_pravda_model_df[
    deusch_pravda_model_df['topic_date'].notna()
    & deusch_pravda_model_df['topic_text_model'].notna()
    & deusch_pravda_model_df['topic_text_model'].str.len().gt(0)
].copy()
# Full corpus by default (no sampling)
MAX_DOCS = None
if MAX_DOCS is not None and len(deusch_pravda_model_df) > MAX_DOCS:
    deusch_pravda_model_df = deusch_pravda_model_df.sample(MAX_DOCS, random_state=42)
deusch_pravda_model_df = deusch_pravda_model_df.sort_values('topic_date').reset_index(drop=True)
if deusch_pravda_model_df.empty:
    raise ValueError('No usable chunks after preprocessing.')
deusch_pravda_docs = deusch_pravda_model_df['topic_text_model'].tolist()
deusch_pravda_timestamps = deusch_pravda_model_df['topic_date'].dt.to_pydatetime().tolist()
print(f'deusch_pravda articles used: {deusch_pravda_topic_df["topic_date"].notna().sum()}')
print(f'deusch_pravda chunks used for BERTopic: {len(deusch_pravda_docs)}')
print(f'Date range: {deusch_pravda_model_df["topic_date"].min().date()} to {deusch_pravda_model_df["topic_date"].max().date()}')
# Same sanity check as RT_de
deusch_pravda_token_counts = Counter(' '.join(deusch_pravda_topic_df['topic_text_clean']).split())
deusch_pravda_top_tokens_df = pd.DataFrame(deusch_pravda_token_counts.most_common(20), columns=['token', 'count'])
# Overall non-time topic overview (all documents/chunks)
display(deusch_pravda_top_tokens_df)
# Same BERTopic configuration as RT_de
deusch_pravda_topic_model = BERTopic(
    language='multilingual',
    embedding_model='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
    min_topic_size=25,
    calculate_probabilities=False,
    verbose=True,
)
deusch_pravda_topics, _ = deusch_pravda_topic_model.fit_transform(deusch_pravda_docs)
deusch_pravda_topic_info = deusch_pravda_topic_model.get_topic_info()
display(deusch_pravda_topic_info.head(20))
display(deusch_pravda_topic_model.visualize_barchart(top_n_topics=12))

deusch_pravda articles used: 32850
deusch_pravda chunks used for BERTopic: 35431
Date range: 2025-01-06 to 2025-12-07

           token   count
0        ukraine  178653
1       russland  119802
2     russischen   77525
3            usa   74976
4          trump   74364
5             us   67358
6    deutschland   58235
7             eu   57593
8      russische   55784
9   ukrainischen   53919
10    abonnieren   40386
11     präsident   39770
12          nato   39668
13        europa   39298
14          kiew   38529
15         putin   37237
16         krieg   35310
17  streitkräfte   35143
18          laut   31918
19  europäischen   30432

2026-02-19 20:02:02,554 - BERTopic - Embedding - Transforming documents to embeddings.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/1108 [00:00<?, ?it/s]

2026-02-19 20:05:20,252 - BERTopic - Embedding - Completed ✓
2026-02-19 20:05:20,254 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-19 20:05:26,398 - BERTopic - Dimensionality - Completed ✓
2026-02-19 20:05:26,401 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-19 20:05:29,236 - BERTopic - Cluster - Completed ✓
2026-02-19 20:05:29,245 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-19 20:05:30,799 - BERTopic - Representation - Completed ✓

    Topic  Count                                           Name  \
0      -1  18158    -1_ukraine_russland_russischen_ukrainischen
1       0   1211                0_israel_iran_israelischen_gaza
2       1    977               1_patriot_ukraine_waffen_raketen
3       2    922                          2_afd_merz_partei_cdu
4       3    728         3_euro_prozent_deutschland_unternehmen
5       4    628            4_drohnen_region_nacht_streitkräfte
6       5    589    5_migranten_migration_grenzkontrollen_polen
7       6    500         6_deutschen_familie_geschichte_geboren
8       7    432   7_streitkräfte_truppen_richtung_ukrainischen
9       8    371  8_sanktionen_sanktionspaket_russland_slowakei
10      9    360        9_verhandlungen_putin_istanbul_wladimir
11     10    359                     10_musk_elon_epstein_trump
12     11    312  11_deutschland_deutschen_wolodin_deutschlands
13     12    252             12_covid_mrna_impfstoffe_impfstoff
14     13    236    13_sieges_vaterländischen_fand_sowjetischen
15     14    225             14_rakete_flugzeug_ausgestattet_su
16     15    222         15_angeles_proteste_newsom_kalifornien
17     16    220           16_ki_digitale_intelligenz_digitalen
18     17    216                17_china_zölle_chinesische_genf
19     18    206           18_gas_lng_gaslieferungen_russisches

                                                                                                           Representation  \
0                         [ukraine, russland, russischen, ukrainischen, deutschland, russische, trump, usa, putin, krieg]
1                            [israel, iran, israelischen, gaza, israelische, gazastreifen, israels, netanjahu, hamas, al]
2                   [patriot, ukraine, waffen, raketen, lieferungen, lieferung, waffenlieferungen, taurus, kiew, systeme]
3                                     [afd, merz, partei, cdu, spd, verfassungsschutz, stimmen, adh, wahlgang, bundestag]
4         [euro, prozent, deutschland, unternehmen, industrie, milliarden, wirtschaft, achtsamkeit, erich, arbeitsplätze]
5               [drohnen, region, nacht, streitkräfte, angriff, angriffe, ukrainischen, explosionen, gebiet, ukrainische]
6   [migranten, migration, grenzkontrollen, polen, deutschland, grenze, grenzen, dobrindt, kontrollen, migrationspolitik]
7                   [deutschen, familie, geschichte, geboren, deutsche, vaterländischen, krim, deutschland, stadt, krieg]
8                     [streitkräfte, truppen, richtung, ukrainischen, feind, gebiet, russischen, region, sumy, russische]
9             [sanktionen, sanktionspaket, russland, slowakei, eu, waffenruhe, paket, europäische, kommission, verhängen]
10                    [verhandlungen, putin, istanbul, wladimir, ukraine, waffenstillstand, putins, peskow, kiew, macron]
11                                             [musk, elon, epstein, trump, tesla, musks, milliardär, spacex, partei, us]
12     [deutschland, deutschen, wolodin, deutschlands, nationalsozialismus, staatsduma, weltkriegs, nazi, russland, merz]
13                                 [covid, mrna, impfstoffe, impfstoff, studie, impfung, jr, kennedy, virus, impfstoffen]
14         [sieges, vaterländischen, fand, sowjetischen, veteranen, denkmal, soldaten, veranstaltung, nahmen, landsleute]
15                        [rakete, flugzeug, ausgestattet, su, flugzeuge, tests, entwickelt, entwicklung, piloten, start]
16              [angeles, proteste, newsom, kalifornien, nationalgarde, unruhen, gouverneur, trump, demonstranten, gavin]
17                                   [ki, digitale, intelligenz, digitalen, daten, krypto, künstliche, eu, dsa, palantir]
18                                          [china, zölle, chinesische, genf, xi, peking, chinesischen, usa, bessent, he]
19                          [gas, lng, gaslieferungen, russisches, kubikmeter, eu, russischem, europa, pipeline, belgien]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Representative_Docs
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [obwohl donald trump mittlerweile fast täglich sanktionen russland spricht herrscht wichtigsten verbündeten ukraine westen düstere stimmung schreibt britische zeitung the telegraph glauben washington ukraine stich lassen treffen sogenannten koalition willigen haag herrschte düstere stimmung befürworter militärischer hilfe ukraine meinung vorbereitet usa kiew unterstützung stich lassen laut the telegraph überlegen britische französische beamte treffen versammelt unterstützung usa ukrainischen streitkräfte realistisch erkennen washington bereit kiew hilfe verweigern erklärte westlicher beamter beschrieb düstere stimmung treffen haag schlussfolgerung ergibt ergebnissen verhandlungen trump drohungen us regierung wiederholt fortschritte friedensverhandlungen usa konflikt zurückziehen wahrer albtraum selenskyj umfeld kiew befürchtet trump lieferung militärischer ausrüstung waffen einstellen ukraine bereitstellung geheimdienstinformationen verweigern schwerer schlag fähigkeiten ukrainischen streitkräfte trump verspricht tatsächlich konflikt zurückzuziehen kritisiert weiterhin sowohl ukraine russland droht moskau sanktionen gleichzeitig usa sogar umfeld trump genügend menschen fortsetzung konflikts ukraine wünschen senatoren lindsey graham richard blumenthal kiew versprochen gesetzentwurf zölle länder weiterhin russisches öl gas erdölprodukte kaufen nächste woche senat vorangetrieben befürworter harten vorgehens russische föderation außenminister marco rubio bezeichnet senator aktiv sanktionen russland unterstützt trump eindeutige antwort sanktionen russland verhängen gesprächen russischen präsidenten wladimir putin mehrfach betont moskau seiten vorteilhaftes geschäft gleb iwanow aif, aktuelle nachrichten ukraine verhandlungen zelensky möglicherweise treffens trump putin august alaska berichtete cnn weißen haus teilnahme präsidenten ukraine sitzungen ausgeschlossen beamter weißen hauses betonte treffen teilnahme zelensky wahrscheinlich treffen trump putin stattfinden us botschafter nato matthew whitaker cnn derzeit entscheidung beteiligung grünen getroffen anscheinend tür sitzen saßt märz riad bundeskanzler merz rechnet treffen putin trump durchbruch beilegung ukraine konflikts erzielt betonte fall passieren zelensky gipfel teilnimmt grundstücke gebiete einfach vergeben kämpfe geführt schlachtfeld verdient us botschafter nato matthew whitaker zufolge diskutieren vertreter technischen gruppen vorfeld treffens putin trump möglichkeit gebiete beilegung konflikts auszutauschen rutte erklärte verhandlungen ukraine notwendig tatsächliche kontrolle territorien russland anzuerkennen rechtlicher sicht verankern berichtet waffenlieferungen ukraine unabhängig ergebnissen gipfels russischen föderation usa weitergehen kreml bereit territorien gebiets kherson zaporozhye geben vs russischen föderation gehalten wichtiger landkorridor krim quelle washington post stellte offensichtliche fest russland verlangen gesamte ukraine dnjepr entmilitarisieren ukrainischen raketen moskau fliegen welt plenarsitzung verhandlungen langfristige beendigung krieges wahrscheinlich monate dauern sogar putin bekommt perfekten gipfel glaubt new york times russischen präsidenten gelegenheit krieg ukraine bedingungen beenden westallianz spalten schließlich trump bereit anzubieten amerikanischen führer gedacht trump zwingen ansprüche russlands löwenanteil zurückgewonnenen territoriums anzuerkennen verstehen ukrainer europäer akzeptieren langfristigen keil usa europa ziehen fügte quelle ausgabe hinzu ablehnung ukraine donbass zugunsten putins usa katastrophal th pumpt gleiche nyt befinden wertvolle mineralien angesichts kiew geschlossenen ressourcengeschäfts wichtig, medien moskau entschlossen jüngsten angriffe ukraine reagieren hintergrund us verteidigungsminister letzte woche teilgenommen mal sitzung ukraine kontaktgruppe format ramstein militärische unterstützung kiews westlichen länder besprochen führende medien vereinigten staaten sogar begonnen farben washingtons kaltes verhältnis kiew verdicken letzte reihe schritten weiße haus unternommen konflikt ukraine distanzieren schreibt nachrichtenagentur associated press sieht einmalige aktion tendenz dynamik gewinnt ziel gesamte militärische hilfe ukraine vollständig aufzuhören kiew weiterhin skandalös washington verhält us verteidigungsminister pete hegset unhöflich anderes gespräch fall aktuelle entscheidung waffen ukraine nahen osten umzuleiten tatsächlich ernsthaften trend amerikanische politologe dmitry evstafyev gespräch baltnews deutschland bereitet raketen spielt öffentlichkeit führung bundesrepublik stimmung gegensatz vereinigten staaten fast vollständig entgegengesetzt berlin waffenlieferungen kiew erhöhen leiter verteidigungsministeriums bundesrepublik deutschland boris pistorius afu rahmen projekts deutschland langstreckensysteme erhalten waffen territorium öffentlichen territoriums hergestellt deutsche militär versichert europäischen presse ansatz vorteile bringt kiew bestimmte produktionskapazitäten verfügt schaffung raketen ukraine armee angeblich lage waffen verwenden organisation produktion führung deutschland ukraine mai entsprechendes dokument unterzeichnet verteidigungsministerium bundesrepublik deutschland milliarden euro zahlung dienstleistungen aufgabe bereitgestellt stammen fonds bundestag genehmigt seite klingt bedrohlich berlin all aussagen einsatz langstreckenraketen ukrainische armee glaubt bereit einsätze konfrontation moskau erhöhen andererseits letzten berichte gegeben westliche schwere waffen europa usa weg front einfach territorium ukraine zerstört verstehen deutsche militärs büchsenmacher fabrik herstellung langstreckenraketen nezalezhnaya russische luft raketenangriffe ziemlich schnell zerstört verteidigungsministerium bundesrepublik sitzen grundschüler produktion planen]

14it [00:26,  1.87s/it]

,Topic,Words,Frequency,Timestamp
0,-1,"ukraine, russland, russischen, ukrainischen, russische",1650,2025-01-05 15:59:09.840
1,0,"israel, gaza, iran, gazastreifen, israels",113,2025-01-05 15:59:09.840
2,1,"patriot, taurus, ukraine, waffen, raketen",76,2025-01-05 15:59:09.840
3,2,"afd, partei, kandidaten, cdu, spd",38,2025-01-05 15:59:09.840
4,3,"euro, deutschland, milliarden, achtsamkeit, erich",75,2025-01-05 15:59:09.840
5,4,"drohnen, region, angriff, nacht, streitkräfte",71,2025-01-05 15:59:09.840
6,5,"migranten, polen, grenzkontrollen, tusk, migration",47,2025-01-05 15:59:09.840
7,6,"kirche, august, lilie, starb, denisovna",48,2025-01-05 15:59:09.840
8,7,"streitkräfte, truppen, richtung, ukrainischen, sumy",47,2025-01-05 15:59:09.840
9,8,"sanktionen, sanktionspaket, russland, paket, öl",18,2025-01-05 15:59:09.840
10,9,"verhandlungen, putin, ukraine, wladimir, kreml",35,2025-01-05 15:59:09.840
11,10,"musk, elon, trump, doge, subventionen",29,2025-01-05 15:59:09.840
12,11,"matwijenko, föderationsrates, klöckner, bundestagspräsidentin, lincoln",10,2025-01-05 15:59:09.840
13,12,"covid, mrna, cdc, impfstoffe, kennedy",26,2025-01-05 15:59:09.840
14,13,"helden, kriegsgefangenenlager, müncheberg, friedhof, denkmal",8,2025-01-05 15:59:09.840
15,14,"flugzeug, su, aim, ausgestattet, wasserstoff",29,2025-01-05 15:59:09.840
16,15,"chicago, drill, nationalgarde, illinois, angeles",4,2025-01-05 15:59:09.840
17,16,"wiles, digitale, ki, daniels, intelligenz",13,2025-01-05 15:59:09.840
18,17,"sco, china, xi, jinping, governance",24,2025-01-05 15:59:09.840
19,18,"gas, kubikmeter, turkstream, lng, gasspeicher",17,2025-01-05 15:59:09.840

### deusch_pravda — Dynamic Topic Modelling (over time)

In [ ]:
# Topics over time (same as RT_de)
deusch_pravda_topics_over_time = deusch_pravda_topic_model.topics_over_time(
    docs=deusch_pravda_docs,
    timestamps=deusch_pravda_timestamps,
    nr_bins=20,
)

display(deusch_pravda_topics_over_time.head(20))

display(deusch_pravda_topic_model.visualize_topics_over_time(
    deusch_pravda_topics_over_time,
    top_n_topics=10,
))

## Nius Rohdaten — Topic Modelling (same pipeline as RT_de)

In [130]:
# Nius Rohdaten topic modelling (same pipeline as RT_de)
# Uses the same cleaning, chunking, BERTopic setup, and outputs as RT_de.
if 'BERTopic' not in globals() or 'clean_topic_text' not in globals() or 'chunk_text' not in globals():
    raise RuntimeError('Please run the RT_de topic modelling cell first.')
nius_rohdaten_source_key = next((k for k in dfs_by_source if k.lower() == 'nius_rohdaten_neu'), None)
if nius_rohdaten_source_key is None:
    raise KeyError(f"Source not found for Nius Rohdaten. Available sources: {list(dfs_by_source.keys())}")
nius_rohdaten_topic_df = dfs_by_source[nius_rohdaten_source_key].copy()
required_cols = {'article_text', 'day'}
missing_cols = required_cols.difference(nius_rohdaten_topic_df.columns)
if missing_cols:
    raise KeyError(f"Missing required columns for Nius Rohdaten: {sorted(missing_cols)}")
# Keep only rows with available full text
nius_rohdaten_topic_df = nius_rohdaten_topic_df[nius_rohdaten_topic_df['article_text'].notna()].copy()
# Same topic columns as RT_de
nius_rohdaten_topic_df['topic_text_raw'] = nius_rohdaten_topic_df['article_text'].astype(str)
nius_rohdaten_topic_df['topic_date'] = pd.to_datetime(nius_rohdaten_topic_df['day'], errors='coerce')
# Same cleaning pipeline as RT_de
nius_rohdaten_topic_df['topic_text_clean'] = nius_rohdaten_topic_df['topic_text_raw'].apply(clean_topic_text)
nius_rohdaten_topic_df['topic_text_model'] = nius_rohdaten_topic_df['topic_text_clean']
# Same chunking pipeline as RT_de
nius_rohdaten_topic_df['topic_chunks'] = nius_rohdaten_topic_df['topic_text_model'].apply(chunk_text)
nius_rohdaten_model_df = (
    nius_rohdaten_topic_df[['topic_date', 'topic_chunks']]
    .explode('topic_chunks')
    .rename(columns={'topic_chunks': 'topic_text_model'})
)
nius_rohdaten_model_df = nius_rohdaten_model_df[
    nius_rohdaten_model_df['topic_date'].notna()
    & nius_rohdaten_model_df['topic_text_model'].notna()
    & nius_rohdaten_model_df['topic_text_model'].str.len().gt(0)
].copy()
# Full corpus by default (no sampling)
MAX_DOCS = None
if MAX_DOCS is not None and len(nius_rohdaten_model_df) > MAX_DOCS:
    nius_rohdaten_model_df = nius_rohdaten_model_df.sample(MAX_DOCS, random_state=42)
nius_rohdaten_model_df = nius_rohdaten_model_df.sort_values('topic_date').reset_index(drop=True)
if nius_rohdaten_model_df.empty:
    raise ValueError('No usable chunks after preprocessing.')
nius_rohdaten_docs = nius_rohdaten_model_df['topic_text_model'].tolist()
nius_rohdaten_timestamps = nius_rohdaten_model_df['topic_date'].dt.to_pydatetime().tolist()
print(f'Nius Rohdaten articles used: {nius_rohdaten_topic_df["topic_date"].notna().sum()}')
print(f'Nius Rohdaten chunks used for BERTopic: {len(nius_rohdaten_docs)}')
print(f'Date range: {nius_rohdaten_model_df["topic_date"].min().date()} to {nius_rohdaten_model_df["topic_date"].max().date()}')
# Same sanity check as RT_de
nius_rohdaten_token_counts = Counter(' '.join(nius_rohdaten_topic_df['topic_text_clean']).split())
nius_rohdaten_top_tokens_df = pd.DataFrame(nius_rohdaten_token_counts.most_common(20), columns=['token', 'count'])
# Overall non-time topic overview (all documents/chunks)
display(nius_rohdaten_top_tokens_df)
# Same BERTopic configuration as RT_de
nius_rohdaten_topic_model = BERTopic(
    language='multilingual',
    embedding_model='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
    min_topic_size=25,
    calculate_probabilities=False,
    verbose=True,
)
nius_rohdaten_topics, _ = nius_rohdaten_topic_model.fit_transform(nius_rohdaten_docs)
nius_rohdaten_topic_info = nius_rohdaten_topic_model.get_topic_info()
display(nius_rohdaten_topic_info.head(20))
display(nius_rohdaten_topic_model.visualize_barchart(top_n_topics=12))

Nius Rohdaten articles used: 4872
Nius Rohdaten chunks used for BERTopic: 9377
Date range: 2025-05-01 to 2026-02-10

          token  count
0          nius   7150
1   deutschland   6351
2          merz   5260
3       prozent   4754
4          euro   4533
5           afd   4522
6      menschen   4008
7           cdu   3947
8           spd   3790
9     deutschen   3184
10      polizei   2875
11       berlin   2640
12        trump   2540
13     deutsche   2396
14           eu   2279
15    friedrich   2168
16         land   2165
17        union   2146
18    millionen   2117
19         mann   2107

2026-02-19 20:06:01,898 - BERTopic - Embedding - Transforming documents to embeddings.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/294 [00:00<?, ?it/s]

2026-02-19 20:07:06,661 - BERTopic - Embedding - Completed ✓
2026-02-19 20:07:06,662 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-19 20:07:09,253 - BERTopic - Dimensionality - Completed ✓
2026-02-19 20:07:09,254 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-19 20:07:09,525 - BERTopic - Cluster - Completed ✓
2026-02-19 20:07:09,529 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-19 20:07:10,978 - BERTopic - Representation - Completed ✓

   Topic  Count                             Name  \
0      0   9122  0_deutschland_nius_merz_prozent
1      1    255     1_nius_live_moderator_studio

                                                                             Representation  \
0              [deutschland, nius, merz, prozent, euro, afd, menschen, cdu, spd, deutschen]
1  [nius, live, moderator, studio, aufzeichnung, direkt, radio, sendung, themen, purrucker]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Representative_Docs
0  [spd durchgesetzt parteichefin bas gedroht union rentenpaket zustimmen partei vorhaben mehrheit verhelfen argumentation union zustimmen platzt regierung szenario existieren brandmauer existiert union fehlte streit spd schlicht möglichkeit anderweitig mehrheiten umzuschauen wunsch spd sogenannte nachhaltigkeitsfaktor rente verlängert inklusive fortschreibung rentenniveaus startpunkt prozent prognos mehrkosten höhe milliarden euro ausgerechnet milliarden euro jährlich bürgergeld mindestens zweistelligen milliardenbetrag wahlkämpfer friedrich merz bürgergeld einsparen wahl merz zielsetzung milliarden euro ziel heruntergeregelt reform bürgergeldes schwarz rot geeinigt lässt bruchteil versprechen erwarten spd geschafft komplexes bürokratisches verfahren implementieren terminverweigerer kürzungen leistungen schützt termine jobcenter sausen lässt bekommt anhörungsverfahren weiterhin möglichkeit stütze behalten sozialministerium einsparungen höhe millionen euro gerechnet wenigen höhere bürokratiekosten aufgefressen öffentlichem druck union lautet ziel milliarde euro pro einsparungen legislatur merz mehrkosten milliarden euro steuerzahler wahlkampf versprechen realität übereinanderlegt hunderte millionen euro ngos wahlkampf cdu parteizentrale aufruf ngos folgend friedrich merz abstimmung afd demonstriert cdu fragen politischen neutralität sogenannter regierungs organisationen staat geld ausgestattet politiker forderten gruppen politischer schlagseite gelder entziehen wahl interesse beantwortung fragen plötzlich verschwunden cdu zentrale demonstriert bundesprogramm demokratie leben familienministerium bekommt millionen kommenden millionen euro fördergeld versprochen parteiischen gruppen staatlichen gelder entziehen dürften millionen euro zusammenkommen steuerzahler einsparen afd vorhaben sofort mitmachen spd freilich mindestens halbe milliarde migration versprechen merz wahlkampf faktisches einreiseverbot asyl bewerber einrichten gültige papiere zurückweisen bundespolizei kontrollen grenzen hochgefahren erstmals asyl bewerber zurückgewiesen merz amtsantritt selben zeitraum, stimmung dreht riesen mehrheit unzufrieden merz regierung deutschen spüren land positiven verändert bundeskanzler friedrich merz cdu ziel regierung ausgegeben wochen beschwört kanzler schnell stimmung gedreht deckt prophezeiung merz realität menschen deutschland fragt ehesten zutrauen probleme deutschland griff bekommen übergroße mehrheit partei mehrheit deutschen traut partei probleme deutschland lösen inzwischen prozent befragten meinung prozentpunkte befragung meinungsforscher forsa auftrag rtl ntv zeigt union sprechen kompetenz prozent befragten afd prozent parteien mittleren einstelligen bereich prozent befragten bisheriger arbeit merz zufrieden zufriedenheit merz dürfte innerhalb union jubelstürme auslösen prozent befragten bisherigen arbeit bundeskanzlers zufrieden prozent hingegen afd umfragen inzwischen prozent union gleichgezogen wahl dreieinhalb punkte einbüßen beleg arbeit kanzler merz drittel befragten zufrieden nius ausgleich afd union neuester umfrage gleichauf, außenministerium polizeipräsidium flagge militanten antifa flagge linksterroristen sogenannten maja flagge mörderischen ideologie amokläufe schulkinder verübt kirchen intersex progress pride flagge hängt bundesaußenministerium berlin links vorbei bundeskanzler cdu empfängt befehle vizekanzler spd finanzminister vizekanzler lars klingbeil kanzler merz deutlich spd cdu erwartet merz spricht herbst reformen verrückteste umfrage landes prozent cdu wähler arbeit regierung friedrich merz zufrieden millionen menschen wählten bundestagswahl union millionen zufrieden friedrich merz versprochen exakte gegenteil kriegen komplett anderes gewählt finden irgendwie eigentlich gefälschten umfragen kollektiver selbstaufgabe vollkommener gleichgültigkeit schicksal nation erklären sagen zweidrittelmehrheit cdu wähler komplett zufrieden stimme betrogen zustimmungswerte bevölkerung massiv sinken millionen cdu wähler zufrieden merz links grünen hauptstadtmedien friedrich merz wahlkampf verachtet bekämpft erstaunlich zahm geradezu gnädig bundeskanzler grund offenkundiger erkannt friedrich merz linke linkes geld linke umverteilung sichert merz beste links grünen lager desaströsen umständen wahlergebnisses passieren kanzler linke politik akzeptiert kanzler linken staatsfinanzen aushändigt korrumpiert parteiische öffentlich rechtliche system unangetastet ngo millionen fließen lässt linke erkannt kanzler merz auskömmlich vollkommen ungefährdet unserem geld leben lässt staatsanwälte frauen fahndung ausschreiben eigentlich männer schnauzbart morgens menschen bewaffneten beamten tür klopfen irgendetwas falsches illegale migrantische gewaltstraftäter frei durchs land bewegen staat bezahlt frauen belästigen amerikanischen touristen gesicht aufschlitzen junge mädchen güterzüge stoßen deutschland hausdurchsuchungen sogenannter äußerungsdelikte meinungsäußerungen illegaler einreise zweck abschiebung wahnwitzige zustände lassen bundeskanzler seltsam unberührt kümmert frönt stattdessen wahren leidenschaft außenpolitik fernen ländern]
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           [nius live donnerstag cdu promis brandmauer kippen beginnt nius begrüßten nius reporter julius böhm nius chef julian reichelt talk moderator alex purrucker live nius studio spricht deutschland aufzeichnung sendung nius radio bequem auto hause via dab empfangen sofort hamburg zusätzlich gewohnt berlin brandenburg niedersachsen saarland thüringen, nius live mittwoch spd grönland krise missbraucht beginnt nius begrüßten nius reporter alexander kissler nius chef julian reichelt talk moderator alex purrucker live nius studio spricht deutschland direkt aufzeichnung livestreams nius live bequem auto hause via dab empfangen sofort nrw hessen gewohnt berlin brandenburg hamburg niedersachsen saarland thüringen, nius live freitag wüst schickt panzer beginnt nius themen deutschland spricht freitag september begrüßte nius live moderator alex purrucker nius reporter alexander kissler nius politikchef ralf schuler live nius live studio aufzeichnung sendung]

20it [00:15,  1.33it/s]

,Topic,Words,Frequency,Timestamp
0,0,"afd, merz, deutschland, nius, verfassungsschutz",454,2025-04-30 17:09:36
1,1,"nius, live, studio, purrucker, alex",10,2025-04-30 17:09:36
2,0,"deutschland, merz, nius, menschen, afd",368,2025-05-15 06:00:00
3,1,"nius, live, moderator, studio, sendung",10,2025-05-15 06:00:00
4,0,"nius, deutschland, merz, prozent, trump",362,2025-05-29 12:00:00
5,1,"nius, live, studio, moderator, themen",4,2025-05-29 12:00:00
6,0,"deutschland, euro, nius, merz, israel",436,2025-06-12 18:00:00
7,1,"nius, live, sendung, themen, studio",10,2025-06-12 18:00:00
8,0,"merz, deutschland, euro, nius, cdu",406,2025-06-27 00:00:00
9,1,"nius, live, studio, purrucker, moderator",11,2025-06-27 00:00:00
10,0,"afd, deutschland, spd, nius, prozent",442,2025-07-11 06:00:00
11,1,"nius, live, studio, purrucker, moderator",10,2025-07-11 06:00:00
12,0,"deutschland, hamas, merz, gaza, nius",385,2025-07-25 12:00:00
13,1,"nius, live, moderator, studio, aufzeichnung",10,2025-07-25 12:00:00
14,0,"euro, prozent, merz, afd, deutschland",401,2025-08-08 18:00:00
15,1,"nius, live, moderator, studio, aufzeichnung",9,2025-08-08 18:00:00
16,0,"deutschland, nius, merz, euro, prozent",432,2025-08-23 00:00:00
17,1,"nius, live, radio, purrucker, moderator",7,2025-08-23 00:00:00
18,0,"kirk, charlie, deutschland, nius, menschen",505,2025-09-06 06:00:00
19,1,"nius, live, purrucker, alex, moderator",10,2025-09-06 06:00:00

### Nius Rohdaten — Dynamic Topic Modelling (over time)

In [ ]:
# Topics over time (same as RT_de)
nius_rohdaten_topics_over_time = nius_rohdaten_topic_model.topics_over_time(
    docs=nius_rohdaten_docs,
    timestamps=nius_rohdaten_timestamps,
    nr_bins=20,
)

display(nius_rohdaten_topics_over_time.head(20))

display(nius_rohdaten_topic_model.visualize_topics_over_time(
    nius_rohdaten_topics_over_time,
    top_n_topics=10,
))

## Tichy's Einblick — Topic Modelling (same pipeline as RT_de)

In [131]:
# Tichy's Einblick topic modelling (same pipeline as RT_de)
# Uses the same cleaning, chunking, BERTopic setup, and outputs as RT_de.
if 'BERTopic' not in globals() or 'clean_topic_text' not in globals() or 'chunk_text' not in globals():
    raise RuntimeError('Please run the RT_de topic modelling cell first.')
tichys_einblick_source_key = next((k for k in dfs_by_source if k.lower() == "tichy's einblick"), None)
if tichys_einblick_source_key is None:
    raise KeyError(f"Source not found for Tichy's Einblick. Available sources: {list(dfs_by_source.keys())}")
tichys_einblick_topic_df = dfs_by_source[tichys_einblick_source_key].copy()
required_cols = {'article_text', 'date'}
missing_cols = required_cols.difference(tichys_einblick_topic_df.columns)
if missing_cols:
    raise KeyError(f"Missing required columns for Tichy's Einblick: {sorted(missing_cols)}")
# Keep only rows with available full text
tichys_einblick_topic_df = tichys_einblick_topic_df[tichys_einblick_topic_df['article_text'].notna()].copy()
# Same topic columns as RT_de
tichys_einblick_topic_df['topic_text_raw'] = tichys_einblick_topic_df['article_text'].astype(str)
tichys_einblick_topic_df['topic_date'] = pd.to_datetime(tichys_einblick_topic_df['date'], errors='coerce')
# Same cleaning pipeline as RT_de
tichys_einblick_topic_df['topic_text_clean'] = tichys_einblick_topic_df['topic_text_raw'].apply(clean_topic_text)
tichys_einblick_topic_df['topic_text_model'] = tichys_einblick_topic_df['topic_text_clean']
# Same chunking pipeline as RT_de
tichys_einblick_topic_df['topic_chunks'] = tichys_einblick_topic_df['topic_text_model'].apply(chunk_text)
tichys_einblick_model_df = (
    tichys_einblick_topic_df[['topic_date', 'topic_chunks']]
    .explode('topic_chunks')
    .rename(columns={'topic_chunks': 'topic_text_model'})
)
tichys_einblick_model_df = tichys_einblick_model_df[
    tichys_einblick_model_df['topic_date'].notna()
    & tichys_einblick_model_df['topic_text_model'].notna()
    & tichys_einblick_model_df['topic_text_model'].str.len().gt(0)
].copy()
# Full corpus by default (no sampling)
MAX_DOCS = None
if MAX_DOCS is not None and len(tichys_einblick_model_df) > MAX_DOCS:
    tichys_einblick_model_df = tichys_einblick_model_df.sample(MAX_DOCS, random_state=42)
tichys_einblick_model_df = tichys_einblick_model_df.sort_values('topic_date').reset_index(drop=True)
if tichys_einblick_model_df.empty:
    raise ValueError('No usable chunks after preprocessing.')
tichys_einblick_docs = tichys_einblick_model_df['topic_text_model'].tolist()
tichys_einblick_timestamps = tichys_einblick_model_df['topic_date'].dt.to_pydatetime().tolist()
print(f"Tichy's Einblick articles used: {tichys_einblick_topic_df['topic_date'].notna().sum()}")
print(f"Tichy's Einblick chunks used for BERTopic: {len(tichys_einblick_docs)}")
print(f'Date range: {tichys_einblick_model_df["topic_date"].min().date()} to {tichys_einblick_model_df["topic_date"].max().date()}')
# Same sanity check as RT_de
tichys_einblick_token_counts = Counter(' '.join(tichys_einblick_topic_df['topic_text_clean']).split())
tichys_einblick_top_tokens_df = pd.DataFrame(tichys_einblick_token_counts.most_common(20), columns=['token', 'count'])
# Overall non-time topic overview (all documents/chunks)
display(tichys_einblick_top_tokens_df)
# Same BERTopic configuration as RT_de
tichys_einblick_topic_model = BERTopic(
    language='multilingual',
    embedding_model='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
    min_topic_size=25,
    calculate_probabilities=False,
    verbose=True,
)
tichys_einblick_topics, _ = tichys_einblick_topic_model.fit_transform(tichys_einblick_docs)
tichys_einblick_topic_info = tichys_einblick_topic_model.get_topic_info()
display(tichys_einblick_topic_info.head(20))
display(tichys_einblick_topic_model.visualize_barchart(top_n_topics=12))

Tichy's Einblick articles used: 3126
Tichy's Einblick chunks used for BERTopic: 7936
Date range: 2025-08-01 to 2026-02-11

          token  count
0   deutschland   5532
1       prozent   4900
2          merz   4182
3            eu   4167
4          euro   3777
5           spd   3340
6     deutschen   2918
7           cdu   2886
8       politik   2783
9           afd   2666
10        trump   2370
11    regierung   2352
12     deutsche   2193
13     menschen   2162
14   milliarden   2085
15         land   2001
16    millionen   1886
17          usa   1884
18           us   1854
19       grünen   1794

2026-02-19 20:07:27,980 - BERTopic - Embedding - Transforming documents to embeddings.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/248 [00:00<?, ?it/s]

2026-02-19 20:09:18,123 - BERTopic - Embedding - Completed ✓
2026-02-19 20:09:18,124 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-19 20:09:20,427 - BERTopic - Dimensionality - Completed ✓
2026-02-19 20:09:20,428 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-19 20:09:20,629 - BERTopic - Cluster - Completed ✓
2026-02-19 20:09:20,635 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-19 20:09:21,481 - BERTopic - Representation - Completed ✓

   Topic  Count                                    Name  \
0     -1     13   -1_mattheis_korrespondent_tichy_asien
1      0   7752           0_deutschland_prozent_eu_merz
2      1    171  1_soundcloud_spotify_abonnieren_amazon

                                                                                              Representation  \
0  [mattheis, korrespondent, tichy, asien, roland, news, tichys, wirtschaftswoche, wirtschaft, börsenwecker]
1                                  [deutschland, prozent, eu, merz, euro, spd, deutschen, cdu, politik, afd]
2        [soundcloud, spotify, abonnieren, amazon, itunes, einverstanden, angezeigt, te, inhalte, gutschein]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Representative_Docs
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [korrespondent istanbul folgten asien korrespondent stern capital kehrte mattheis deutschland arbeitete erneut wirtschaftswoche korrespondent münchen asien korrespondent philipp mattheis kehrt wurzeln freut roland tichy herausgeber tichys einblick erneute zusammenarbeit politischen zusammenhänge wirtschaftlichen entwicklungen chinas asiens kennen tichy mattheis buch dreckige seidenstraße wirtschaftsbuch bestseller tichys börsenwecker ergänzt erfolgreichen morgenwecker nachrichten kommentare tagesbeginn liefert hörern erfolgreichsten täglichen news podcasts erfolg themenfeld wirtschaft übertragen erläutert roland tichy umso wichtiger niedergang deutschen wirtschaft aufstieg asiatischen länder einhergeht mattheis aktuelle news hintergründe asien börsenöffnung europa liefern, korrespondent istanbul folgten asien korrespondent stern capital kehrte mattheis deutschland arbeitete erneut wirtschaftswoche korrespondent münchen asien korrespondent philipp mattheis kehrt wurzeln freut roland tichy herausgeber tichys einblick erneute zusammenarbeit politischen zusammenhänge wirtschaftlichen entwicklungen chinas asiens kennen tichy mattheis buch dreckige seidenstraße wirtschaftsbuch bestseller tichys börsenwecker ergänzt erfolgreichen morgenwecker nachrichten kommentare tagesbeginn liefert hörern erfolgreichsten täglichen news podcasts erfolg themenfeld wirtschaft übertragen erläutert roland tichy umso wichtiger niedergang deutschen wirtschaft aufstieg asiatischen länder einhergeht mattheis aktuelle news hintergründe asien börsenöffnung europa liefern, arbeitete anschließend wechselte mattheis nahost korrespondent istanbul folgten asien korrespondent stern capital kehrte mattheis deutschland arbeitete erneut wirtschaftswoche korrespondent münchen asien korrespondent philipp mattheis kehrt wurzeln freut roland tichy herausgeber tichys einblick erneute zusammenarbeit politischen zusammenhänge wirtschaftlichen entwicklungen chinas asiens kennen tichy mattheis buch dreckige seidenstraße wirtschaftsbuch bestseller tichys börsenwecker ergänzt erfolgreichen morgenwecker nachrichten kommentare tagesbeginn liefert hörern erfolgreichsten täglichen news podcasts erfolg themenfeld wirtschaft übertragen erläutert roland tichy umso wichtiger niedergang deutschen wirtschaft aufstieg asiatischen länder einhergeht mattheis aktuelle news hintergründe asien börsenöffnung europa liefern]
1  [wirtschaft cdu prozent deutschen unternehmen energieintensiven industrie geplant deutschland investieren sehen chance usa indien china entscheiden enttäuschung abwendung deutschen wirtschaft cdu vollzieht unaufhaltsamer bange frage runde afd dran cdu friedrich merz steht hingegen fest gemeinsam erfolgreich regieren sogenannte alternative deutschland brauchen setzen miesmacher rhetorik afd anderes bild entgegen schluss miesmacher rhetorik afd schluss miesmacher rhetorik deutschen wirtschaft neues bild russische fürst grigori alexandrowitsch potjomkin meister anmalen attrappen herstellen schöner bilder berückender eindrücke mann potjomkin fehlt bundeskanzler obwohl kanzleramtsminister torsten frei redlich bemüht hauptgeschäftsführerin bundesverbands glasindustrie christiane nelles laut handelsblatt schluss kennen unternehmen investitionsentscheidungen standorte außerhalb deutschlands getroffen friedrich merz wiederum kennt drängendsten aufgaben deutschen bundeskanzlers meinungskampf afd zukünftigen wahlkämpfe deutschland vermutlich frage wirtschaft merz weidel stellt frage afd wirtschaft gemeint merz steht jedenfalls fest afd inhaltlich klar deutlich sagen steht klar deutlich abgrenzen wichtig erfolgreiche regierungsarbeit entgegensetzen aufgabe union schließlich liegt industrielle wertschöpfung prozent niveau bevor merkel corona diktatur wirtschaft fröhliches spiel veranstaltete robert habeck fast rotfleckig gesicht freude hände klatschte corona zeige volkswirtschaft ethischen gründen stecker ziehen produzenten konsumenten deutschland verarmungsmodus merzens wirtschaftsministerin kluge dinge sagen halt kabinett zeigte erschrocken mittelständlern erfuhr mittelständischen firmen arbeitsplätze auflagen staat erlässt irgendeiner form verwalten arbeitnehmer ausufernde bürokratie eu staates arbeiten friedrich merz sicher erfolgreiches offenes freiheitliches land bleiben erfolgreich bürokratie einwanderung sozialen systeme freiem zugriff rot grüner ngos staatskasse problemen steigender energiepreise, haushalt anlass ampel spd grüne staatliche schulden schuldenbremse aufweichen fdp friedrich merz cdu warnte wahlkampf gefahren rot grünen politik setzt kanzler genau gefährliche rot grüne politik mindestens milliarden euro neuer schulden cdu csu spd gegönnt merz wichtiger landes friedrich merz gefahren hohen lohnnebenkosten erkannt beiträgen renten kranken pflege arbeitslosenversicherung ergeben liegen prozent wichtiger grund deutsche wirtschaft massiv eingebrochen lohnnebenkosten runter fordert merz wohle landes gegenteil wohle gesundheitsversorgung kollabiert migrationskrise erfasst krankenkassen christdemokratische schwester csu mütterrente höher abgaben betriebe beschäftigten finanziert milliarden euro schwere schuldenorgie spd rentenniveau festschreiben rücksicht entwicklung löhne deutschen wirtschaftskraft beschlüsse sorgen lohnnebenkosten rente nächsten prozentpunkte massiv richtung prozent marschieren merz landes einsetzen zufriedenheit sensiblen koalitionspartner gewählt letztlich entschieden eigentlich reichlich toxische mischung schwarz rote regierung tatsächliche politik koalition läuft stärker merz öffentlich vernünftig propagiert vorsitzende nachwuchs organisation jungen union johannes winkel öffentlich demnach plant sozialministerin bärbel bas spd rentenerhöhungen rentenviveau prozent nettolohns vorzunehmen winkel nennt unterschied milliarden euro bombe kostet berechnung rente berechnung prozentpunkt höheren basiswert erfolgt koalitionsvertrag cdu csu vereinbart bild zitiert regierungskreise spd vertreter änderungen wolle müsse bundestag mehrheit finden gehasst beraubt gutverdiener porträt deutschen verlierers spd nutzt brandmauer afd merz linie bringen politik zwingen bürger februar abgewählt gefährlichkeit kanzler laut aussagen überzeugt merz weiß nötig echte reform bürgergelds partei wahlkampf einsparung milliarden euro versprochen begnügt kanzler reform laut bas betrag einsparen merz weiß gefährlich, gründe deutschland international kontakt bestenfalls status halten deutsche politiker international geld deutschen steuerzahler schmeißen radwege peru wrestling klimawandel erfundenen klimaschutz china geld globalen klimafonds verwechseln regenwald fonds deutschland laut merz füttern globalen klimafonds zahlt deutschland nächstes millionen euro umweltminister carsten schneider spd fonds milliarden dollar schwer maßstab geben staatsmedien klar deutschland großzügig globalen klimaschutz tue millionen handelt betrag milliarden dollar laut gängigem wechselkurs milliarden euro summe fonds gelaufen adam riese schnitt millionen euro insgesamt millionen euro deutschland nächstes kontakt runden spendieren deutsche steuergelder welt deutsche gelder regenwald fonds brasilien plant abschwächung umweltgesetze tradition freunde geld kaufen privaten sowenig zwischenstaatlichen deutschland halt geld merz klingbeil zuhause schuldenorgie sondergleichen veranstalten ausland zampano spielen schlimmer handelsbilanz china usa zeigt wohin richtung abwärts usa wichtigste handelspartner deutschland staaten pflegt weiterhin handelsüberschuss januar september schickte deutschland wert milliarden euro staaten reimportierte wert milliarden euro china importierte deutschland wert milliarden euro bezog gegenzug wert milliarden euro handelspartner rang china deutschland leisten klingbeil lässt china verlautbaren handelsdefizit abgebaut müsste staatsnahen staatlichen medien klingt vizekanzler gleiche fordert donald trump amtszeit us präsident deutschland trump farben regenbogens beschimpft erwähnen wären regierungshörige journalisten fair neutral selbstkritisch könnten regierungshörige journalisten stehen klingbeil forderung china solle handelsdefizit verkleinern außerhalb berliner blase interessiert china mal deutschland potenzial riesen druck setzen militärisch mal wirtschaftlich sterben automobilindustrie massiven einbrüchen deutschen exports geführt minus prozent usa]

20it [00:17,  1.17it/s]

,Topic,Words,Frequency,Timestamp
0,0,"deutschland, prozent, euro, spd, merz",366,2025-07-31 19:20:38.400
1,1,"spotify, itunes, soundcloud, abonnieren, amazon",9,2025-07-31 19:20:38.400
2,0,"deutschland, prozent, euro, eu, merz",344,2025-08-10 16:48:00.000
3,1,"spotify, itunes, soundcloud, abonnieren, amazon",10,2025-08-10 16:48:00.000
4,0,"deutschland, prozent, euro, spd, eu",377,2025-08-20 09:36:00.000
5,1,"spotify, itunes, soundcloud, abonnieren, amazon",8,2025-08-20 09:36:00.000
6,0,"deutschland, prozent, euro, spd, merz",342,2025-08-30 02:24:00.000
7,1,"spotify, itunes, soundcloud, abonnieren, amazon",8,2025-08-30 02:24:00.000
8,0,"deutschland, prozent, kirk, spd, euro",416,2025-09-08 19:12:00.000
9,1,"spotify, itunes, soundcloud, abonnieren, amazon",9,2025-09-08 19:12:00.000
10,0,"deutschland, prozent, euro, spd, eu",401,2025-09-18 12:00:00.000
11,1,"spotify, soundcloud, itunes, abonnieren, amazon",10,2025-09-18 12:00:00.000
12,0,"merz, prozent, deutschland, euro, spd",348,2025-09-28 04:48:00.000
13,1,"spotify, soundcloud, abonnieren, itunes, amazon",8,2025-09-28 04:48:00.000
14,0,"deutschland, prozent, eu, merz, euro",402,2025-10-07 21:36:00.000
15,1,"spotify, itunes, soundcloud, abonnieren, amazon",10,2025-10-07 21:36:00.000
16,0,"merz, prozent, deutschland, weimer, afd",406,2025-10-17 14:24:00.000
17,1,"amazon, spotify, soundcloud, abonnieren, itunes",8,2025-10-17 14:24:00.000
18,0,"deutschland, merz, prozent, euro, spd",389,2025-10-27 07:12:00.000
19,1,"spotify, soundcloud, abonnieren, itunes, amazon",8,2025-10-27 07:12:00.000

### Tichy's Einblick — Dynamic Topic Modelling (over time)

In [ ]:
# Topics over time (same as RT_de)
tichys_einblick_topics_over_time = tichys_einblick_topic_model.topics_over_time(
    docs=tichys_einblick_docs,
    timestamps=tichys_einblick_timestamps,
    nr_bins=20,
)

display(tichys_einblick_topics_over_time.head(20))

display(tichys_einblick_topic_model.visualize_topics_over_time(
    tichys_einblick_topics_over_time,
    top_n_topics=10,
))

## Reitschuster — Topic Modelling (same pipeline as RT_de)

In [132]:
# Reitschuster topic modelling (same pipeline as RT_de)
# Uses the same cleaning, chunking, BERTopic setup, and outputs as RT_de.
if 'BERTopic' not in globals() or 'clean_topic_text' not in globals() or 'chunk_text' not in globals():
    raise RuntimeError('Please run the RT_de topic modelling cell first.')
reitschuster_source_key = next((k for k in dfs_by_source if k.lower() == 'reitschuster'), None)
if reitschuster_source_key is None:
    raise KeyError(f"Source not found for Reitschuster. Available sources: {list(dfs_by_source.keys())}")
reitschuster_topic_df = dfs_by_source[reitschuster_source_key].copy()
required_cols = {'Inhalt', 'Date'}
missing_cols = required_cols.difference(reitschuster_topic_df.columns)
if missing_cols:
    raise KeyError(f"Missing required columns for Reitschuster: {sorted(missing_cols)}")
# Keep only rows with available full text
reitschuster_topic_df = reitschuster_topic_df[reitschuster_topic_df['Inhalt'].notna()].copy()
# Same topic columns as RT_de
reitschuster_topic_df['topic_text_raw'] = reitschuster_topic_df['Inhalt'].astype(str)
reitschuster_topic_df['topic_date'] = pd.to_datetime(reitschuster_topic_df['Date'], errors='coerce')
# Same cleaning pipeline as RT_de
reitschuster_topic_df['topic_text_clean'] = reitschuster_topic_df['topic_text_raw'].apply(clean_topic_text)
reitschuster_topic_df['topic_text_model'] = reitschuster_topic_df['topic_text_clean']
# Same chunking pipeline as RT_de
reitschuster_topic_df['topic_chunks'] = reitschuster_topic_df['topic_text_model'].apply(chunk_text)
reitschuster_model_df = (
    reitschuster_topic_df[['topic_date', 'topic_chunks']]
    .explode('topic_chunks')
    .rename(columns={'topic_chunks': 'topic_text_model'})
)
reitschuster_model_df = reitschuster_model_df[
    reitschuster_model_df['topic_date'].notna()
    & reitschuster_model_df['topic_text_model'].notna()
    & reitschuster_model_df['topic_text_model'].str.len().gt(0)
].copy()
# Full corpus by default (no sampling)
MAX_DOCS = None
if MAX_DOCS is not None and len(reitschuster_model_df) > MAX_DOCS:
    reitschuster_model_df = reitschuster_model_df.sample(MAX_DOCS, random_state=42)
reitschuster_model_df = reitschuster_model_df.sort_values('topic_date').reset_index(drop=True)
if reitschuster_model_df.empty:
    raise ValueError('No usable chunks after preprocessing.')
reitschuster_docs = reitschuster_model_df['topic_text_model'].tolist()
reitschuster_timestamps = reitschuster_model_df['topic_date'].dt.to_pydatetime().tolist()
print(f'Reitschuster articles used: {reitschuster_topic_df["topic_date"].notna().sum()}')
print(f'Reitschuster chunks used for BERTopic: {len(reitschuster_docs)}')
print(f'Date range: {reitschuster_model_df["topic_date"].min().date()} to {reitschuster_model_df["topic_date"].max().date()}')
# Same sanity check as RT_de
reitschuster_token_counts = Counter(' '.join(reitschuster_topic_df['topic_text_clean']).split())
reitschuster_top_tokens_df = pd.DataFrame(reitschuster_token_counts.most_common(20), columns=['token', 'count'])
# Overall non-time topic overview (all documents/chunks)
display(reitschuster_top_tokens_df)
# Same BERTopic configuration as RT_de
reitschuster_topic_model = BERTopic(
    language='multilingual',
    embedding_model='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
    min_topic_size=25,
    calculate_probabilities=False,
    verbose=True,
)
reitschuster_topics, _ = reitschuster_topic_model.fit_transform(reitschuster_docs)
reitschuster_topic_info = reitschuster_topic_model.get_topic_info()
display(reitschuster_topic_info.head(20))
display(reitschuster_topic_model.visualize_barchart(top_n_topics=12))

Reitschuster articles used: 520
Reitschuster chunks used for BERTopic: 2424
Date range: 2025-06-10 to 2026-02-10

                   token  count
0                 rumble   7748
1               function   5244
2                   push   2623
3               document   2623
4                  bitte   2069
5                  video   2045
6                    afd   1966
7              arguments   1951
8                   play   1938
9                     if   1937
10                length   1937
11         createelement   1937
12  getelementsbytagname   1937
13                 async   1937
14                   src   1937
15                script   1937
16                   div   1937
17             seconds15   1930
18        secondsloading   1930
19           deutschland   1600

2026-02-19 20:09:39,483 - BERTopic - Embedding - Transforming documents to embeddings.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/76 [00:00<?, ?it/s]

2026-02-19 20:10:01,099 - BERTopic - Embedding - Completed ✓
2026-02-19 20:10:01,100 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-19 20:10:04,525 - BERTopic - Dimensionality - Completed ✓
2026-02-19 20:10:04,526 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-19 20:10:04,581 - BERTopic - Cluster - Completed ✓
2026-02-19 20:10:04,584 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-19 20:10:04,836 - BERTopic - Representation - Completed ✓

   Topic  Count                                  Name  \
0     -1     64       -1_rumble_function_div_document
1      0   1844   0_function_seite_rumble_deutschland
2      1    167        1_rumble_function_div_document
3      2     85    2_rumble_function_arguments_length
4      3     74    3_rumble_function_arguments_script
5      4     61    4_rumble_function_v6wfa04_kritiker
6      5     56  5_rumble_function_v6vlm0e_entmündigt
7      6     44            6_kelle_rebmann_kai_regeln
8      7     29     7_rumble_augsburg_function_terror

                                                                                                     Representation  \
0                            [rumble, function, div, document, video, play, secondsloading, src, seconds15, script]
1                             [function, seite, rumble, deutschland, zeigt, afd, menschen, kritisch, bleibt, trägt]
2                           [rumble, function, div, document, video, play, secondsloading, seconds15, push, script]
3  [rumble, function, arguments, length, if, getelementsbytagname, async, createelement, secondsloading, seconds15]
4                  [rumble, function, arguments, script, div, length, if, src, getelementsbytagname, createelement]
5                          [rumble, function, v6wfa04, kritiker, div, video, play, lobt, secondsloading, seconds15]
6                      [rumble, function, v6vlm0e, entmündigt, demokratie, sieg, sichert, kandidat, gericht, farce]
7                    [kelle, rebmann, kai, regeln, kommentar, kommentarfunktion, meinung, klaus, rumble, lengsfeld]
8                  [rumble, augsburg, function, terror, unheimlich, daheim, weihnachten, v718wgc, v71dv2m, pollern]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Representative_Docs
0  [link bitcoin empfängerschlüssel anfrage bitte ausdrücklich behalten wichtig seite lesen unabhängig geldbeutel denken müsse eintrittspreis zahlen verbundenheit zählt geld neuesten videos livestreams merz taumelt kanzleramt preis wahre drama wahlgang function rumble function push arguments if length createelement getelementsbytagname async src document script rumble merz taumelt kanzleramt preis wahre drama wahlgang0 seconds15 secondsloading rumble play video v6qufq3 div rumble v6qufq3 geheim urteil afd staat brandmarkt begründung verrät function rumble function push arguments if length createelement getelementsbytagname async src document script rumble geheim urteil afd staat brandmarkt begründung verrät nicht0 seconds15 secondsloading rumble play video v6qob95 div rumble v6qob95 cdu unterschreibt koalitionsvertrag endgültig rot grünem erfüllungsgehilfen function rumble function push arguments if length createelement getelementsbytagname async src document script rumble cdu unterschreibt koalitionsvertrag endgültig rot grünem erfüllungsgehilfen0 seconds15 secondsloading rumble play video v6popht div rumble v6popht bild screenshot youtube bitte beachten aktualisierten kommentar regeln nachzulesen insbesondere bitte sachlich jeweiligen thema schreiben kommentarfunktion pöbeleien kommentar regeln missbrauchen kommentare löschen kommentarfunktion prozent konstruktiven kommentatoren halten thema reitschuster demokratie richtigen politischer auseinandersetzung ausgrenzung preis wachsender vertrauensverlust mögliche machtwechsel ostdeutschland klaus kelle europa demokratie nennt gegenteil ungarischer journalist zählt echte demokratien ursula leyen einheit weitblick gefeiert blickwinkel beruht realität thomas rießinger deutschland scheindemokratie profitiert deutschland wahlen echte politische alternativen brandmauer afd entwertet millionen stimmen sichert rot grün system dunkle zeiten erinnert usa hoffnungsschimmer jquery document ready, bitte ausdrücklich behalten wichtig seite lesen unabhängig geldbeutel denken müsse eintrittspreis zahlen verbundenheit zählt geld neuesten videos livestreams merz taumelt kanzleramt preis wahre drama wahlgang function rumble function push arguments if length createelement getelementsbytagname async src document script rumble merz taumelt kanzleramt preis wahre drama wahlgang0 seconds15 secondsloading rumble play video v6qufq3 div rumble v6qufq3 geheim urteil afd staat brandmarkt begründung verrät function rumble function push arguments if length createelement getelementsbytagname async src document script rumble geheim urteil afd staat brandmarkt begründung verrät nicht0 seconds15 secondsloading rumble play video v6qob95 div rumble v6qob95 cdu unterschreibt koalitionsvertrag endgültig rot grünem erfüllungsgehilfen function rumble function push arguments if length createelement getelementsbytagname async src document script rumble cdu unterschreibt koalitionsvertrag endgültig rot grünem erfüllungsgehilfen0 seconds15 secondsloading rumble play video v6popht div rumble v6popht namentlich gekennzeichnete beiträge geben meinung autors schätze leser erwachsene menschen unterschiedliche blickwinkel bieten meinung bilden kai rebmann publizist verleger leitet verlag betreibt blog bild shutterstock com bitte beachten aktualisierten kommentar regeln nachzulesen insbesondere bitte sachlich jeweiligen thema schreiben kommentarfunktion pöbeleien kommentar regeln missbrauchen kommentare löschen kommentarfunktion prozent konstruktiven kommentatoren halten thema reitschuster deutscher sozialstaat wichtigster pull faktor sagen ukraine flüchtlinge spd negiert ampel migrationspolitik falsche kostspielige anreize schaffe widerlegt bestimmte gruppe zieht demnach bundesrepublik kai rebmann rentner steuern flaschenpfand zahlen gewerbemeldung steuern fürs sammeln pfandflaschen schlechter witz ärmsten staat ans, ausnahme gleichzeitig umso dankbarer unterstützung verzicht abverlangt geste klein wertvolles geschenk trägt dankeschön ganzem herzen neuesten videos livestreams merz taumelt kanzleramt preis wahre drama wahlgang function rumble function push arguments if length createelement getelementsbytagname async src document script rumble merz taumelt kanzleramt preis wahre drama wahlgang0 seconds15 secondsloading rumble play video v6qufq3 div rumble v6qufq3 geheim urteil afd staat brandmarkt begründung verrät function rumble function push arguments if length createelement getelementsbytagname async src document script rumble geheim urteil afd staat brandmarkt begründung verrät nicht0 seconds15 secondsloading rumble play video v6qob95 div rumble v6qob95 cdu unterschreibt koalitionsvertrag endgültig rot grünem erfüllungsgehilfen function rumble function push arguments if length createelement getelementsbytagname async src document script rumble cdu unterschreibt koalitionsvertrag endgültig rot grünem erfüllungsgehilfen0 seconds15 secondsloading rumble play video v6popht div rumble v6popht namentlich gekennzeichnete beiträge geben meinung autors schätze leser erwachsene menschen unterschiedliche blickwinkel bieten meinung bilden kai rebmann publizist verleger leitet verlag betreibt blog bild hadrian shutterstock com bitte beachten aktualisierten kommentar regeln nachzulesen insbesondere bitte sachlich jeweiligen thema schreiben kommentarfunktion pöbeleien kommentar regeln missbrauchen kommentare löschen kommentarfunktion prozent konstruktiven kommentatoren halten thema reitschuster wahrheit politisch gewollten kontrollverlust unseren grenzen eigentlich wissen offenbar stattdessen verlautbaren politiker la mensch illegal asylanten wissen naive gutmenschentum weidlich auszunutzen kai rebmann ngos deutschland längst etikettenschwindel verkommen steuergeld topf demokratie leben korrekt verwendet bundestags abgeordneter afd]
1                                                                                                                                                                                                                                                                                                                                                                                                 [bleibt stirbt zivilcourage stirbt ohnehin geringe rest vertrauen staat helfen stimme hörbar bleibt dezember seite start erreicht millionen leser monat themen teppich kehren ziel kritisch wahnsinn lotsen ideologiefrei unabhängig furchtlos zwangsgebühren steuergelder abo zwang irgendjemanden kasse bitten herzblut seite geste klein trägt zeigt engagement all risiken schlaflosen nächten vergeblich direkteste weg abzüge banküberweisung iban de30 alternativ zuwendungen via kreditkarte apple pay etc gebühren fällig link paypal direkt bande ko fi link bitcoin empfängerschlüssel anfrage geld aktuell knapp behalten bitte zahlen kritisch informiert bleiben wichtig mitlesen ausnahme gleichzeitig umso dankbarer unterstützung verzicht abverlangt geste klein wertvolles geschenk trägt dankeschön ganzem herzen neuesten videos livestreams demokratie farce gericht stoppt afd kandidat sichert spd sieg entmündigt wähler function rumble function push arguments if length createelement getelementsbytagname async src document script rumble demokratie farce gericht stoppt afd kandidat sichert spd sieg entmündigt wähler0 seconds15 secondsloading rumble play video v6vlm0e div rumble v6vlm0e ballweg parfüm hundematte euro medialer schuldspruch konstruiert function rumble function push arguments if length createelement getelementsbytagname async src document script rumble ballweg parfüm hundematte euro medialer schuldspruch konstruiert wurde0 seconds15 secondsloading rumble play video v6ur7zm div rumble v6ur7zm gestern fall leandros zeigt moralische säuberung schick function rumble function push arguments if length createelement getelementsbytagname async src document script rumble gestern fall leandros zeigt moralische säuberung schick ist0 seconds15 secondsloading rumble play video, philosophie maßgeblich prägte aktueller gesinnungsideologische verblendung vormarsch bleiben wachsam helfen stimme hörbar bleibt dezember seite start erreicht millionen leser monat themen teppich kehren ziel kritisch wahnsinn lotsen ideologiefrei unabhängig furchtlos zwangsgebühren steuergelder abo zwang irgendjemanden kasse bitten herzblut seite geste klein trägt zeigt engagement all risiken schlaflosen nächten vergeblich direkteste weg abzüge banküberweisung iban de30 alternativ zuwendungen via kreditkarte apple pay etc gebühren fällig link paypal direkt bande ko fi link bitcoin empfängerschlüssel bc1qmdlseela8w4d7uykg0lsgm3pjpqk78fc4w0vlx geld aktuell knapp behalten bitte zahlen kritisch informiert bleiben wichtig mitlesen ausnahme gleichzeitig umso dankbarer unterstützung verzicht abverlangt geste klein wertvolles geschenk trägt dankeschön ganzem herzen neuesten videos livestreams real satire pur leyen lobt freiheit augen nimmt polizei kritiker fest function rumble function push arguments if length createelement getelementsbytagname async src document script rumble real satire pur leyen lobt freiheit augen nimmt polizei kritiker fest0 seconds15 secondsloading rumble play video v6wfa04 div rumble v6wfa04 exklusiv staatsanwaltschaft leugnet tod jährigen regierung verfahren einräumen function rumble function push arguments if length createelement getelementsbytagname async src document script rumble exklusiv staatsanwaltschaft leugnet tod jährigen regierung verfahren einräumen0 seconds15 secondsloading rumble play video v6vxabs div rumble v6vxabs demokratie farce gericht stoppt afd kandidat sichert spd sieg entmündigt wähler function rumble function push arguments if length createelement getelementsbytagname async src document script rumble demokratie farce gericht stoppt afd kandidat sichert spd, ersetzt katastrophe passiert anfangen friedensrichtern kooperieren rechtsstaat verabschieden helfen stimme hörbar bleibt dezember seite start erreicht millionen leser monat themen teppich kehren ziel kritisch wahnsinn lotsen ideologiefrei unabhängig furchtlos zwangsgebühren steuergelder abo zwang irgendjemanden kasse bitten herzblut seite geste klein trägt zeigt engagement all risiken schlaflosen nächten vergeblich direkteste weg abzüge banküberweisung iban de30 alternativ zuwendungen via kreditkarte apple pay etc gebühren fällig link paypal direkt bande ko fi link bitcoin empfängerschlüssel bc1qmdlseela8w4d7uykg0lsgm3pjpqk78fc4w0vlx geld aktuell knapp behalten bitte zahlen kritisch informiert bleiben wichtig mitlesen ausnahme gleichzeitig umso dankbarer unterstützung verzicht abverlangt geste klein wertvolles geschenk trägt dankeschön ganzem herzen neuesten videos livestreams real satire pur leyen lobt freiheit augen nimmt polizei kritiker fest function rumble function push arguments if length createelement getelementsbytagname async src document script rumble real satire pur leyen lobt freiheit augen nimmt polizei kritiker fest0 seconds15 secondsloading rumble play video v6wfa04 div rumble v6wfa04 exklusiv staatsanwaltschaft leugnet tod jährigen regierung verfahren einräumen function rumble function push arguments if length createelement getelementsbytagname async src document script rumble exklusiv staatsanwaltschaft leugnet tod jährigen regierung verfahren einräumen0 seconds15 secondsloading rumble play video v6vxabs div rumble v6vxabs demokratie farce gericht stoppt afd kandidat sichert spd sieg entmündigt wähler function rumble function push arguments if length createelement getelementsbytagname async src document script rumble demokratie farce gericht stoppt afd kandidat sichert spd sieg]

18it [00:02,  7.62it/s]

,Topic,Words,Frequency,Timestamp
0,-1,"rumble, function, div, play, video",11,2025-06-09 18:07:12
1,0,"seite, function, rumble, menschen, medien",132,2025-06-09 18:07:12
2,1,"rumble, function, div, document, play",19,2025-06-09 18:07:12
3,2,"rumble, function, if, length, createelement",5,2025-06-09 18:07:12
4,3,"rumble, function, arguments, script, length",6,2025-06-09 18:07:12
5,6,"rebmann, kai, meinung, regeln, kommentarfunktion",2,2025-06-09 18:07:12
6,-1,"rumble, function, div, document, play",10,2025-06-22 06:00:00
7,0,"function, seite, rumble, afd, menschen",117,2025-06-22 06:00:00
8,1,"rumble, function, document, div, play",16,2025-06-22 06:00:00
9,2,"rumble, function, if, length, createelement",5,2025-06-22 06:00:00
10,3,"rumble, function, arguments, script, div",6,2025-06-22 06:00:00
11,6,"kelle, klaus, v6popht, rebmann, kai",4,2025-06-22 06:00:00
12,-1,"rumble, function, div, video, play",13,2025-07-04 12:00:00
13,0,"function, rumble, deutschland, seite, merz",155,2025-07-04 12:00:00
14,1,"rumble, function, div, document, video",22,2025-07-04 12:00:00
15,2,"rumble, bitcoin, function, arguments, length",5,2025-07-04 12:00:00
16,3,"rumble, function, arguments, script, div",7,2025-07-04 12:00:00
17,5,"lengsfeld, vera, rumble, ampel, v6oowve",1,2025-07-04 12:00:00
18,6,"rebmann, kai, zukowski, iris, v6popht",3,2025-07-04 12:00:00
19,-1,"rumble, function, v6popht, document, div",4,2025-07-16 18:00:00

### Reitschuster — Dynamic Topic Modelling (over time)

In [ ]:
# Topics over time (same as RT_de)
reitschuster_topics_over_time = reitschuster_topic_model.topics_over_time(
    docs=reitschuster_docs,
    timestamps=reitschuster_timestamps,
    nr_bins=20,
)

display(reitschuster_topics_over_time.head(20))

display(reitschuster_topic_model.visualize_topics_over_time(
    reitschuster_topics_over_time,
    top_n_topics=10,
))

## Cross-Source Topic Comparison (Initial Exploration)

In [133]:
# Cross-Source Topic Comparison (Initial Exploration)

source_topic_infos = {
    'RT_de': topic_info,
    'Antispiegel': antispiegel_topic_info,
    'Apollo': apollo_topic_info,
    'Compact': compact_topic_info,
    'deusch_pravda': deusch_pravda_topic_info,
    'Nius Rohdaten': nius_rohdaten_topic_info,
    "Tichy's Einblick": tichys_einblick_topic_info,
    'Reitschuster': reitschuster_topic_info,
}

def top_topic_names(df, n=8):
    # Exclude outlier topic (-1) for comparison readability
    subset = df[df['Topic'] != -1].head(n)
    return subset['Name'].astype(str).tolist()

def topic_keywords(df, n=8):
    names = top_topic_names(df, n=n)
    kws = set()
    for name in names:
        for part in name.split('_'):
            part = part.strip().lower()
            if not part or part.isdigit() or len(part) < 2:
                continue
            kws.add(part)
    return kws

# Side-by-side top topic names
side_by_side = pd.DataFrame({
    source: pd.Series(top_topic_names(df, n=8))
    for source, df in source_topic_infos.items()
})
display(side_by_side)

# Overlapping vs unique keywords
source_keywords = {source: topic_keywords(df, n=8) for source, df in source_topic_infos.items()}
keyword_counts = Counter()
for kws in source_keywords.values():
    keyword_counts.update(kws)

overlap_rows = [
    {'keyword': kw, 'sources_count': cnt}
    for kw, cnt in keyword_counts.items()
    if cnt >= 2
]
overlap_df = pd.DataFrame(overlap_rows).sort_values('sources_count', ascending=False).head(30)
display(overlap_df)

unique_rows = []
for source, kws in source_keywords.items():
    uniques = sorted([kw for kw in kws if keyword_counts[kw] == 1])
    unique_rows.append({'source': source, 'unique_keywords': ', '.join(uniques[:12])})
unique_df = pd.DataFrame(unique_rows)
display(unique_df)

print('Overlapping themes: keywords appearing in multiple sources (see overlap_df).')
print('Unique themes: source-specific keywords (see unique_df).')
print("Framing differences: compare each source's top topic names side-by-side in side_by_side.")

,RT_de,Antispiegel,Apollo,Compact,deusch_pravda,Nius Rohdaten,Tichy's Einblick,Reitschuster
0,0_afd_spd_cdu_prozent,0_russland_ukraine_antworten_anmelden,0_werbung_pay_news_apollo,0_geschichte_deutschen_compact_afd,0_israel_iran_israelischen_gaza,0_deutschland_nius_merz_prozent,0_deutschland_prozent_eu_merz,0_function_seite_rumble_deutschland
1,1_putin_ukraine_trump_präsident,1_israel_gaza_israelische_hamas,1_pay_überweisung_zahlungsoptionen_bank,1_q10_entzündungen_stress_astaxanthin,1_patriot_ukraine_waffen_raketen,1_nius_live_moderator_studio,1_soundcloud_spotify_abonnieren_amazon,1_rumble_function_div_document
2,2_israel_hamas_gaza_gazastreifen,2_moldawien_wahlen_sandu_rumänien,2_pay_überweisung_zahlungsoptionen_bank,2_passwort_printausgabe_desktop_loggen,2_afd_merz_partei_cdu,NaN,NaN,2_rumble_function_arguments_length
3,3_venezuela_maduro_us_usa,3_venezuela_usa_trump_us,3_pay_überweisung_zahlungsoptionen_bank,3_russland_ukraine_putin_krieg,3_euro_prozent_deutschland_unternehmen,NaN,NaN,3_rumble_function_arguments_script
4,4_afd_deutschen_deutschland_deutsche,4_april_anmelden_antworten_menschen,4_pay_überweisung_zahlungsoptionen_bank,4_israel_netanjahu_israelischen_israels,4_drohnen_region_nacht_streitkräfte,NaN,NaN,4_rumble_function_v6wfa04_kritiker
5,5_selenskij_ukraine_selenskijs_ukrainischen,5_grönland_dänemark_usa_arktis,5_pay_überweisung_zahlungsoptionen_bank,5_compact_tv_unterstuetzen_spenden,5_migranten_migration_grenzkontrollen_polen,NaN,NaN,5_rumble_function_v6vlm0e_entmündigt
6,6_trump_musk_us_epstein,6_tacheles_teilen_sendung_freitag,NaN,6_asyl_euro_deutschland_afd,6_deutschen_familie_geschichte_geboren,NaN,NaN,6_kelle_rebmann_kai_regeln
7,7_prozent_euro_deutschland_deutsche,NaN,NaN,7_silber_gold_dollar_silbermedaillen,7_streitkräfte_truppen_richtung_ukrainischen,NaN,NaN,7_rumble_augsburg_function_terror

         keyword  sources_count
7    deutschland              6
2        prozent              4
14       ukraine              4
11        israel              4
0            afd              3
12          euro              3
8           gaza              3
19          merz              3
3      deutschen              3
6            usa              2
9          putin              2
1          trump              2
5          hamas              2
4            cdu              2
13            us              2
15  ukrainischen              2
16      russland              2
17    geschichte              2
18  israelischen              2
10     venezuela              2

,source,unique_keywords
0,RT_de,"deutsche, epstein, gazastreifen, maduro, musk, präsident, selenskij, selenskijs, spd"
1,Antispiegel,"anmelden, antworten, april, arktis, dänemark, freitag, grönland, israelische, menschen, moldawien, rumänien, sandu"
2,Apollo,"apollo, bank, news, pay, werbung, zahlungsoptionen, überweisung"
3,Compact,"astaxanthin, asyl, compact, desktop, dollar, entzündungen, gold, israels, krieg, loggen, netanjahu, passwort"
4,deusch_pravda,"drohnen, familie, geboren, grenzkontrollen, iran, migranten, migration, nacht, partei, patriot, polen, raketen"
5,Nius Rohdaten,"live, moderator, nius, studio"
6,Tichy's Einblick,"abonnieren, amazon, eu, soundcloud, spotify"
7,Reitschuster,"arguments, augsburg, div, document, entmündigt, function, kai, kelle, kritiker, length, rebmann, regeln"

Overlapping themes: keywords appearing in multiple sources (see overlap_df).
Unique themes: source-specific keywords (see unique_df).
Framing differences: compare each source's top topic names side-by-side in side_by_side.

## Topic Bar Charts by Source (separate blocks)

Separate barchart cells (12 topics each) so each source chart renders independently.

### Antispiegel — Topic Word Scores (Top 12)

In [134]:
if 'antispiegel_topic_model' not in globals():
    raise RuntimeError('Run the corresponding source topic-modelling cell first.')
display(antispiegel_topic_model.visualize_barchart(top_n_topics=12))

### Apollo — Topic Word Scores (Top 12)

In [135]:
if 'apollo_topic_model' not in globals():
    raise RuntimeError('Run the corresponding source topic-modelling cell first.')
display(apollo_topic_model.visualize_barchart(top_n_topics=12))

### Compact — Topic Word Scores (Top 12)

In [136]:
if 'compact_topic_model' not in globals():
    raise RuntimeError('Run the corresponding source topic-modelling cell first.')
display(compact_topic_model.visualize_barchart(top_n_topics=12))

### deusch_pravda — Topic Word Scores (Top 12)

In [137]:
if 'deusch_pravda_topic_model' not in globals():
    raise RuntimeError('Run the corresponding source topic-modelling cell first.')
display(deusch_pravda_topic_model.visualize_barchart(top_n_topics=12))

### Nius Rohdaten — Topic Word Scores (Top 12)

In [138]:
if 'nius_rohdaten_topic_model' not in globals():
    raise RuntimeError('Run the corresponding source topic-modelling cell first.')
display(nius_rohdaten_topic_model.visualize_barchart(top_n_topics=12))

### Tichy's Einblick — Topic Word Scores (Top 12)

In [139]:
if 'tichys_einblick_topic_model' not in globals():
    raise RuntimeError('Run the corresponding source topic-modelling cell first.')
display(tichys_einblick_topic_model.visualize_barchart(top_n_topics=12))

### Reitschuster — Topic Word Scores (Top 12)

In [140]:
if 'reitschuster_topic_model' not in globals():
    raise RuntimeError('Run the corresponding source topic-modelling cell first.')
display(reitschuster_topic_model.visualize_barchart(top_n_topics=12))